/** Product UI text only. User-authored content is never translated by this catalog. */
export const englishUi: Readonly<Record<string,string>> = {
  "menu.file": "File",
  "menu.task": "Task",
  "刚刚": "Just now",
  "{0} 分钟": "{0} min",
  "{0} 小时": "{0} hr",
  "{0} 天": "{0} days",
  "待开始": "Not started",
  "进行中": "In progress",
  "运行中": "Running",
  "等待处理": "Needs attention",
  "已完成": "Completed",
  "失败": "Failed",
  "已停止": "Stopped",
  "已中断": "Interrupted",
  "状态待核对": "Status unconfirmed",
  "已取消": "Cancelled",
  "阻塞": "Blocked",
  "D Code 导航区": "D Code navigation",
  "收起导航区": "Hide navigation",
  "新建任务": "New task",
  "搜索": "Search",
  "灵感": "Inspiration",
  "最近工作": "Recent work",
  "项目": "Projects",
  "新建项目": "New project",
  "新建项目 ⇧⌘N": "New project ⇧⌘N",
  "更多项目操作 {0}": "More actions for {0}",
  "更多": "More",
  "编辑项目": "Edit project",
  "查看 {0} 的文件": "View files in {0}",
  "查看文件": "View files",
  "在 {0} 中新建任务": "New task in {0}",
  "任务": "Tasks",
  "设置": "Settings",
  "D Code 工作区": "D Code workspace",
  "显示导航区": "Show navigation",
  "新任务": "New task",
  "当前成员对话：{0}": "Current member conversation: {0}",
  "返回主对话": "Return to main conversation",
  "主对话": "Main conversation",
  "个人任务": "Personal task",
  "工作目录": "Working directory",
  "返回任务": "Return to task",
  "对话路径": "Conversation paths",
  "历史路径": "Historical path",
  "当前路径": "Current path",
  " · 当前": " · Current",
  "上下文与运行依据": "Context and run sources",
  "文件与 Git": "Files and Git",
  "打开文件详情": "Open file details",
  "任务操作": "Task actions",
  "先处理定向、历史续写或未保存图片草稿，再开始新对话": "Resolve the directed message, historical continuation, or unsaved image draft before starting a new conversation",
  "开始新一段对话": "Start a new conversation",
  "重命名任务": "Rename task",
  "归档任务": "Archive task",
  "移入废纸篓（仅空任务）": "Move to Trash (empty tasks only)",
  "复制完整会话为新任务": "Copy full conversation to a new task",
  "任务概览": "Task overview",
  "任务暂时无法刷新，当前内容可能已过期。": "This task could not be refreshed. The displayed content may be out of date.",
  "重新读取": "Reload",
  "任务引用的灵感": "Inspiration referenced by this task",
  "下次运行的灵感": "Inspiration for the next run",
  "查看 ": "View ",
  " · 第 ": " · Version ",
  " 版": " ",
  "暂时无法读取任务": "Could not load this task",
  "重试": "Retry",
  "重新连接": "Reconnect",
  "正在读取工作台…": "Loading workspace…",
  "新灵感": "New inspiration",
  "返回当前主对话": "Return to the current main conversation",
  "关闭文件覆盖层": "Close file overlay",
  "文件详情": "File details",
  "文件": "Files",
  "返回对话": "Return to conversation",
  "展开文件内容": "Expand file content",
  "收起文件详情": "Hide file details",
  "运行服务已退出": "The runtime service has exited",
  "任务记录已保留。重新连接后可继续工作。": "Task records are saved. Reconnect to continue.",
  "正在重新连接…": "Reconnecting…",
  "将空任务移入废纸篓": "Move empty task to Trash",
  "任务名称": "Task name",
  "”的记录会保留，可从设置中的已归档任务恢复。": "” will be kept. You can restore it in Settings → Archived tasks.",
  "取消": "Cancel",
  "正在保存…": "Saving…",
  "确认": "Confirm",
  "导入 Pi 会话": "Import Pi conversation",
  "关闭上下文": "Close context",
  "已用来源": "Sources used",
  "关闭来源": "Close source",
  "执行需要处理": "Execution needs attention",
  "子会话": "Child conversations",
  "历史对话": "Conversation history",
  "{0} 小时 {1} 分": "{0} hr {1} min",
  "{0} 分 {1} 秒": "{0} min {1} sec",
  "{0} 秒": "{0} sec",
  "本次执行": "This run",
  "消息": "Messages",
  "工作项 ": "Work item ",
  "查看整体报告；任务仍需单独验收": "View the overall report; the task still requires separate acceptance",
  "核对在途结果后继续": "Check pending results, then continue",
  "核对中断结果后继续": "Check interrupted results, then continue",
  "等待协调者形成阶段": "Waiting for the coordinator to define stages",
  "处理阶段阻塞与返工": "Resolve stage blockers and rework",
  "核对证据并形成整体报告": "Check evidence and prepare the overall report",
  "等待协调者派发当前阶段": "Waiting for the coordinator to dispatch the current stage",
  "等待成员结果与独立验收": "Waiting for member results and independent verification",
  "关闭任务概览": "Close task overview",
  "进度": "Progress",
  "工作流 · ": "Workflow · ",
  "已停止后续推进": "Further work stopped",
  "中断待核对": "Interrupted; review required",
  "查看工作流": "View workflow",
  "正在读取安排": "Loading the plan",
  "当前阶段：": "Current stage: ",
  "尚未形成": "Not yet defined",
  "原因：": "Reason: ",
  "成员：": "Members: ",
  "待派发": "Awaiting dispatch",
  "已验收阶段 ": "Accepted stages ",
  " · 当前阶段成员报告 ": " · Reports from current stage members ",
  "下一步：": "Next: ",
  "尚未制定工作清单": "No work list yet",
  "审查": "Review",
  " 次 · ": " times · ",
  "协调复核通过": "Coordinator review passed",
  "需要返工": "Rework required",
  "需要复查": "Recheck required",
  "独立检查通过，待复核": "Independent check passed; awaiting review",
  "发现问题，待复核": "Issues found; awaiting review",
  "待独立检查": "Awaiting independent check",
  " 次审查的差异": " review differences",
  "关闭": "Close",
  "审查身份": "Review identity",
  "团队": "Team",
  "等待处理{0}": "Needs attention{0}",
  "没有等待事项": "Nothing pending",
  "交付物": "Deliverables",
  "验收报告": "Verification report",
  "综合报告": "Combined report",
  "成员报告": "Member report",
  "成员": "Members",
  "尚无交付物": "No deliverables yet",
  "验收反馈": "Acceptance feedback",
  "需要调整的地方（可选）": "Changes needed (optional)",
  "验收通过": "Accept task",
  "提交反馈": "Submit feedback",
  "执行报告": "Execution report",
  "记录详情": "Record details",
  "对象详情": "Object details",
  "关闭详情": "Close details",
  "独立验收通过": "Independent verification passed",
  "独立验收未通过": "Independent verification failed",
  "已安排返工": "Rework assigned",
  "已安排复验": "Recheck assigned",
  "待协调者复核": "Awaiting coordinator review",
  "成果问题": "Issues in the result",
  "验收依据": "Verification sources",
  " 项独立检查记录": " independent check records",
  "记录已保存，可在相关产物与执行过程查看详情。": "Record saved. View details in the related artifact and execution history.",
  "打开产物": "Open artifact",
  "此记录已不可用。关闭后可选择其他交付物。": "This record is no longer available. Close it to choose another deliverable.",
  "搜索任务": "Search tasks",
  "搜索任务与消息": "Search tasks and messages",
  "搜索任务与消息…": "Search tasks and messages…",
  "关闭搜索": "Close search",
  "消息搜索暂不可用：": "Message search unavailable: ",
  "正在搜索…": "Searching…",
  "没有匹配结果": "No matches",
  "输入关键词查找任务和消息": "Enter a keyword to find tasks and messages",
  "项目已保存，但界面尚未确认刷新：{0}。请重新读取，勿重复创建。": "Project saved, but the interface has not confirmed the refresh: {0}. Reload instead of creating it again.",
  "项目名称": "Project name",
  "项目文件夹": "Project folder",
  "选择文件夹…": "Choose folder…",
  "任务与对话会保留，后续工作使用新目录。": "Tasks and conversations will be kept. Subsequent work uses the new folder.",
  "同时移动项目文件": "Move project files too",
  "目标需为同一磁盘上的空文件夹，已有文件不会被合并或覆盖。": "Choose an empty folder on the same disk. Existing files will not be merged or overwritten.",
  "目录更换尚未完成": "Folder change is incomplete",
  "重新核对目录状态": "Check folder status again",
  "重新读取已保存项目": "Reload saved project",
  "保存项目": "Save project",
  "创建项目": "Create project",
  "后台活动": "Background activity",
  "当前对话": "Current conversation",
  "后台活动状态待核对": "Background activity status unconfirmed",
  "命令在后台运行": "Command running in the background",
  "命令正在运行": "Command running",
  "停止 {0} 的后台活动": "Stop background activity for {0}",
  "当前成员": "Current member",
  "正在停止…": "Stopping…",
  "停止": "Stop",
  "搜索技能": "Search skills",
  "正在读取技能与命令…": "Loading skills and commands…",
  "没有匹配的技能；已知命令仍可直接输入完整名称调用。": "No matching skills. You can still invoke a known command by typing its full name.",
  "{0} 项": "{0} items",
  "↑↓ 选择 · Enter 使用 · Esc 关闭": "↑↓ Select · Enter Use · Esc Close",
  "关闭技能菜单": "Close skills menu",
  "查看本任务工作流": "View this task's workflow",
  "编辑旧消息后继续": "Edit an earlier message and continue",
  "从历史消息继续": "Continue from an earlier message",
  " · 原路径会保留，已完成的文件操作不会撤销": " · The original path is kept; completed file operations are not undone",
  "取消，恢复原草稿": "Cancel and restore draft",
  "正在查看历史路径": "Viewing a historical path",
  "返回当前对话": "Return to current conversation",
  "关闭提示": "Close notice",
  "松开以添加图片或文件": "Drop to add images or files",
  "图片 {0}": "Image {0}",
  "移除图片 {0}": "Remove image {0}",
  "已过期": "Expired",
  "未发送时保留 1 天": "Kept for 1 day before sending",
  "预览 {0}": "Preview {0}",
  "移除附件 {0}": "Remove attachment {0}",
  "所选成员不可接续或不在当前任务，请重新选择": "The selected member cannot continue or is not in this task. Choose again.",
  "发送给 ": "Send to ",
  "取消定向发送": "Cancel directed message",
  "搜索项目文件": "Search project files",
  "正在搜索项目文件…": "Searching project files…",
  "请先进入一个项目任务，再搜索该项目文件。": "Open a project task before searching its files.",
  "输入文件名以搜索当前项目。": "Enter a filename to search this project.",
  "项目文件未搜索完整，请输入更具体的文件名或路径。": "The project search is incomplete. Enter a more specific filename or path.",
  "没有匹配的项目文件。": "No matching project files.",
  "引用指向当前项目文件；部分二进制格式暂不能在工作台预览。": "This reference points to a current project file. Some binary formats cannot be previewed in the workspace yet.",
  "选择子代理": "Choose a member",
  "执行": "Implementation",
  "验收": "Verification",
  "调研": "Research",
  "暂无子代理，可直接请协调者分工": "No members yet. Ask the coordinator to delegate work.",
  "任务消息": "Task message",
  "继续这项任务…": "Continue this task…",
  "描述你想完成的任务，输入 / 选择技能…": "Describe what you want to accomplish. Type / to choose a skill…",
  "任务归属": "Task scope",
  "独立任务": "Personal task",
  "发送时机": "Send timing",
  "排到后面": "Queue after this reply",
  "补充当前工作": "Steer current work",
  "$ 子代理": "$ Members",
  "选择思考强度": "Choose reasoning level",
  "思考强度": "Reasoning level",
  "思考 · {0}": "Reasoning · {0}",
  "发送": "Send",
  "正在读取模型与连接…": "Loading models and connections…",
  "正在读取附件…": "Loading attachments…",
  "正在提交…": "Submitting…",
  "可以继续补充，新消息会在当前回复结束后发送。": "You can add more information. New messages are sent after the current reply ends.",
  "选择模型后即可发送。": "Choose a model to send.",
  "添加一句说明后即可发送。": "Add a description to send.",
  "附件已暂存，未发送时保留 1 天；发送后保留 30 天。": "Attachments are kept for 1 day before sending and 30 days after sending.",
  "添加内容": "Add content",
  "添加": "Add",
  "附件": "Attachment",
  "目标": "Goal",
  "工作流": "Workflow",
  "正在读取当前可用能力…": "Loading available capabilities…",
  "当前没有可从输入区调用的技能、命令或模板。": "No skills, commands, or templates are currently available from the composer.",
  " 搜索文件": " Search files",
  " 查找技能": " Find skills",
  " 选择子代理": " Choose a member",
  "只显示当前可调用能力": "Only currently available capabilities are shown",
  "系统与工具": "System and tools",
  "用户输入": "User input",
  "助手回复": "Assistant replies",
  "思考": "Reasoning",
  "工具结果": "Tool results",
  "正在查看历史路径，当前上下文用量不可用于这条路径。": "You are viewing a historical path. Current context usage does not apply to it.",
  "这条会话当前没有活动运行实例，暂无可读取的上下文用量。": "This conversation has no active runtime, so context usage is unavailable.",
  "模型已切换，等待新回复确认这条会话的上下文用量。": "Model changed. Waiting for a new reply to confirm context usage.",
  "上下文已压缩，等待新回复确认压缩后的用量。": "Context compacted. Waiting for a new reply to confirm usage after compaction.",
  "还没有可核对的模型用量响应，暂无法显示上下文估算。": "No verifiable model usage response yet. A context estimate is unavailable.",
  "连接中，暂无法确认上下文用量。": "Connecting. Context usage cannot be confirmed yet.",
  "正在核对所选模型的上下文用量。": "Checking context usage for the selected model.",
  "当前会话上下文预计剩余 {0}%；查看用量详情": "Estimated remaining context: {0}%. View usage details.",
  "当前会话上下文用量未知；查看详情": "Context usage unknown. View details.",
  "未知": "Unknown",
  "约{0}%": "~{0}%",
  "当前会话上下文": "Conversation context",
  "关闭上下文用量详情": "Close context usage details",
  " 的上下文容量": " context capacity",
  "已用 · 估算": "Used · Estimate",
  "模型容量": "Model capacity",
  "剩余 · 估算": "Remaining · Estimate",
  " token（约": " tokens (~",
  "最近模型用量响应：": "Latest model usage response: ",
  "时间未知": "Time unknown",
  "。这是估算锚点；当前占用可能包含后续消息的估算，不是计费数。": ". This is an estimate anchor; current usage may include estimates for subsequent messages. It is not billing data.",
  "正在读取构成估算…": "Loading the breakdown…",
  "暂时无法读取构成估算。": "The estimated breakdown is temporarily unavailable.",
  "构成估算": "Estimated breakdown",
  " · 估算": " · Estimate",
  "分项按消息内容估算，仅用于了解构成；不是计费或缓存命中数据。": "Each category is estimated from message content to explain the breakdown. It is not billing or cache hit data.",
  "已复制": "Copied",
  "复制失败，点击重试": "Copy failed. Click to retry.",
  "正在复制": "Copying",
  "复制消息": "Copy message",
  "等待处理的扩展请求": "Pending extension requests",
  "当前任务": "Current task",
  "请选择": "Choose an option",
  "提交中…": "Submitting…",
  "会话已导入，但未能打开任务：{0}": "Conversation imported, but the task could not be opened: {0}",
  "关闭导入": "Close import",
  "导入后创建独立任务，原会话保持不变。": "Import creates a separate task. The original conversation stays unchanged.",
  "正在查找会话…": "Finding conversations…",
  "没有可导入的会话。": "No conversations available to import.",
  "未命名会话": "Untitled conversation",
  " 条消息": " messages",
  " · 已导入过": " · Previously imported",
  "正在打开…": "Opening…",
  "正在导入…": "Importing…",
  "打开已导入任务": "Open imported task",
  "导入": "Import",
  "选择": "Select",
  "点击查看灵感，拖动移动；按住 Shift 可多选。": "Click to view an idea. Drag to move it. Hold Shift to select multiple ideas.",
  "平移": "Pan",
  "按住并拖动画布，移动整个视图；灵感位置保持不变。": "Drag the canvas to move the view. Idea positions stay unchanged.",
  "框选": "Marquee select",
  "按住并拖出选框，一次选择多条灵感；Shift 可追加选择。": "Drag a selection rectangle to select multiple ideas. Shift adds to the selection.",
  "连线": "Connect",
  "先点击一条灵感作为起点，再点击另一条连接。": "Click one idea as the starting point, then another to connect them.",
  "{0}需要至少 2 条灵感。{1}": "{0} requires at least 2 ideas. {1}",
  "请清除搜索后重试。": "Clear the search and try again.",
  "请先恢复灵感并返回画布。": "Restore ideas and return to the canvas first.",
  "请先新建灵感。": "Create an idea first.",
  "已选好起点，请点击另一条灵感作为终点。": "Starting point selected. Click another idea as the endpoint.",
  "已取消这两条灵感的连线。": "Connection removed between these ideas.",
  "已连接两条灵感。再选这两条可取消连线，Esc 返回选择。": "Ideas connected. Select them again to disconnect, or press Esc to return to selection.",
  "成组": "Group",
  "成组需要至少选择 2 条灵感。拖出选框，再点击成组。": "Select at least 2 ideas to group them. Drag a selection rectangle, then click Group.",
  "灵感分组": "Idea group",
  "已将 {0} 条灵感成组。": "Grouped {0} ideas.",
  "正在读取灵感…": "Loading ideas…",
  "灵感暂不可用。": "Ideas are temporarily unavailable.",
  "临时平移：按住并拖动画布，松开空格返回原工具。": "Temporary pan: drag the canvas. Release Space to return to the previous tool.",
  "正在保存连线，请稍候。": "Saving the connection. Please wait.",
  "起点已选好，请点击另一条灵感作为终点；Esc 取消。": "Starting point selected. Click another idea as the endpoint; Esc cancels.",
  "灵感工作区": "Inspiration workspace",
  "搜索灵感": "Search ideas",
  "搜索灵感…": "Search ideas…",
  "从当前任务保存": "Save from current task",
  "返回画布": "Return to canvas",
  "已归档 {0}": "Archived {0}",
  "新建灵感": "New idea",
  "关闭灵感提示": "Close inspiration notice",
  "灵感画布": "Inspiration canvas",
  "画布工具": "Canvas tools",
  "将选中灵感成组": "Group selected ideas",
  "成组：先框选或按住 Shift 选择至少 2 条灵感。": "Group: use a selection rectangle or hold Shift to select at least 2 ideas.",
  "将选中的 {0} 条灵感成组": "Group {0} selected ideas",
  "保存中": "Saving",
  "画布操作提示": "Canvas tips",
  "没有找到匹配的灵感。": "No matching ideas.",
  "取消分组 {0}": "Ungroup {0}",
  "灵感连线": "Idea connections",
  "灵感 {0}": "Idea {0}",
  "视频链接": "Video link",
  "添加说明与内容": "Add a description and content",
  "没有已归档灵感": "No archived ideas",
  "把想法留在这里": "Keep your ideas here",
  "归档的灵感可以随时恢复。": "Archived ideas can be restored at any time.",
  "保存文字、图片、链接和视频，整理后用于任务。": "Save text, images, links, and videos. Organize them for your tasks.",
  "新建文字灵感": "New text idea",
  "缩小画布": "Zoom out",
  "放大画布": "Zoom in",
  "适应全部灵感": "Fit all ideas",
  "已选择 {0} 条": "{0} selected",
  "{0} 条灵感": "{0} ideas",
  " · 正在保存…": " · Saving…",
  "编辑灵感": "Edit idea",
  "草稿尚未保留": "Draft not saved yet",
  "保存草稿中…": "Saving draft…",
  "草稿已保留": "Draft saved",
  "类型": "Type",
  "灵感类型": "Idea type",
  "标题": "Title",
  "灵感标题": "Idea title",
  "视频链接（或添加本地文件）": "Video link (or add a local file)",
  "链接地址": "Link URL",
  "灵感链接": "Idea link",
  "图片文件": "Image file",
  "视频文件": "Video file",
  "灵感媒体文件": "Idea media file",
  "无法读取文件路径，请通过文件选择器重新选择。": "Could not read the file path. Select it again using the file picker.",
  "选择图片…": "Choose image…",
  "选择视频…": "Choose video…",
  "保存后会长期保留媒体副本。": "A media copy is kept permanently after saving.",
  "内容": "Content",
  "灵感内容": "Idea content",
  "写下想法，支持 Markdown…": "Write an idea. Markdown supported…",
  "标签": "Tags",
  "灵感标签": "Idea tags",
  "用逗号分隔": "Separate with commas",
  "放弃这份未发布的编辑草稿？已保存的灵感保留。": "Discard this unpublished edit draft? The saved idea will be kept.",
  "继续编辑": "Continue editing",
  "放弃草稿": "Discard draft",
  "保存灵感": "Save idea",
  "已选灵感": "Selected ideas",
  "已选择 ": "Selected ",
  " 条灵感": " ideas",
  "清除灵感选择": "Clear idea selection",
  "切换到选择工具，可拖动这些灵感一起移动；点击成组可整理到同一分组。": "Switch to the selection tool to move these ideas together. Click Group to organize them.",
  "灵感详情": "Idea details",
  "关闭灵感详情": "Close idea details",
  "灵感详情内容": "Idea details content",
  "来源与引用": "Sources and references",
  "第 ": "Version ",
  " 版 · ": " · ",
  "来源：": "Source: ",
  "在灵感中创建": "Created in Inspiration",
  "任务引用": "Task reference",
  "当前版本": "Current version",
  "较早版本": "Earlier version",
  "尚未引用到任务。": "Not referenced by a task yet.",
  "尚未填写正文。": "No content entered yet.",
  "放大查看图片": "Enlarge image",
  "播放本地视频": "Play local video",
  "打开视频链接": "Open video link",
  "打开原始链接": "Open original link",
  "编辑": "Edit",
  "查看 Markdown": "View Markdown",
  "恢复到画布": "Restore to canvas",
  "归档": "Archive",
  "引用到任务": "Reference in a task",
  "灵感引用目标任务": "Task to reference this idea",
  "暂无任务": "No tasks yet",
  "引用此版本": "Reference this version",
  "创建独立任务并引用": "Create a separate task with this reference",
  "渲染失败": "Rendering failed",
  "Mermaid 渲染中…": "Rendering Mermaid…",
  "图片链接": "Image link",
  "选择模型": "Choose model",
  "正在读取模型…": "Loading models…",
  "搜索可用模型": "Search available models",
  "搜索模型或供应商…": "Search models or providers…",
  "没有匹配的模型": "No matching models",
  "还没有已连接的模型，请先配置连接。": "No connected models yet. Set up a connection first.",
  "正在刷新…": "Refreshing…",
  "刷新模型目录": "Refresh model catalog",
  "管理模型与连接": "Manage models and connections",
  "模型回退顺序": "Model fallback order",
  "正在查询…": "Checking…",
  "刷新配额": "Refresh quotas",
  "按顺序选择可用模型。": "Available models are selected in order.",
  "适用剩余额度高于 {0}% 才会自动选用，低额度或未知时检查下一个。": "Automatic selection requires remaining quota above {0}%. Low or unknown quota moves to the next candidate.",
  "配额门槛以模型设置为准，正在读取当前设置。": "The quota threshold comes from model settings. Loading the current setting.",
  "未单独配置，将沿用创建成员时主对话选用的模型。": "No separate configuration. Uses the main conversation's model when the member is created.",
  "请选择一个模型": "Choose a model",
  "原模型已不在目录中": "The original model is no longer in the catalog",
  "未启用，派发时会跳过": "Not enabled; will be skipped during dispatch",
  "当前不可访问": "Currently inaccessible",
  "正在查询额度…": "Checking quota…",
  "首选": "Preferred",
  "备用 {0}": "Fallback {0}",
  "候选模型 {0}": "Model candidate {0}",
  "（已不可用）": "(unavailable)",
  " · 剩余 {0}%": " · {0}% remaining",
  " · {0}更新": " · Updated {0}",
  "上移候选 {0}": "Move candidate {0} up",
  "下移候选 {0}": "Move candidate {0} down",
  "移除候选 {0}": "Remove candidate {0}",
  "添加备用模型": "Add fallback model",
  "需要钥匙串访问授权": "Keychain access required",
  "等待系统钥匙串授权…": "Waiting for system Keychain permission…",
  "钥匙串访问未获允许": "Keychain access denied",
  "已取消本次钥匙串授权": "Keychain permission cancelled",
  "钥匙串授权已超时": "Keychain permission timed out",
  "登录待更新": "Login needs updating",
  "登录已超时，请重试": "Login timed out. Try again.",
  "连接已保存，目录更新失败": "Connection saved; catalog refresh failed",
  "未连接": "Not connected",
  "连接已保存": "Connection saved",
  "已连接": "Connected",
  "需要重新登录": "Sign in again",
  "请完成授权步骤": "Complete the authorization steps",
  "等待浏览器授权": "Waiting for browser authorization",
  "正在连接…": "Connecting…",
  "连接未完成": "Connection incomplete",
  "已取消连接": "Connection cancelled",
  "钥匙串暂不可访问，可在此重新请求授权。": "Keychain is temporarily inaccessible. You can request access again here.",
  "钥匙串中未找到原有连接，请重新配置连接。": "The previous connection was not found in Keychain. Set it up again.",
  "授权窗口未能完成，请重新登录。": "Authorization did not complete. Sign in again.",
  "供应商授权未完成，请重新登录。": "Provider authorization did not complete. Sign in again.",
  "授权已返回，但连接未能保存，请重新登录。": "Authorization returned, but the connection could not be saved. Sign in again.",
  "连接已保存，请重试更新模型目录。": "Connection saved. Retry refreshing the model catalog.",
  "请输入有效的 API Key。": "Enter a valid API Key.",
  "另一项连接正在处理，请稍后重试。": "Another connection is being processed. Try again shortly.",
  "连接服务暂不可用，请稍后重试。": "The connection service is temporarily unavailable. Try again shortly.",
  "连接失败，请检查后重试。": "Connection failed. Check the settings and try again.",
  "密钥已保存，模型目录更新失败。请重试更新。": "Key saved, but the model catalog could not be refreshed. Retry the refresh.",
  "连接结果尚未确认，请刷新连接状态后检查。": "Connection result unconfirmed. Refresh the connection status to check.",
  "{0} 连接": "{0} connection",
  "等待设备码授权": "Waiting for device code authorization",
  "首次使用时会验证模型访问权限。": "Model access is verified on first use.",
  "下次使用时自动更新授权。": "Authorization is automatically refreshed on next use.",
  "当前使用已有的外部连接。": "Currently using an existing external connection.",
  "授权访问钥匙串": "Allow Keychain access",
  "打开登录页面": "Open sign-in page",
  "等待输入授权结果…": "Waiting for authorization result…",
  "输入授权结果": "Enter authorization result",
  "输入 API Key": "Enter API Key",
  "连接中…": "Connecting…",
  "连接": "Connect",
  "取消授权": "Cancel authorization",
  "取消连接": "Cancel connection",
  "重试更新": "Retry refresh",
  "更换密钥": "Replace key",
  "重新登录": "Sign in again",
  "断开 D Code 连接": "Disconnect D Code",
  "使用系统环境或供应商配置连接。": "Connect using system environment variables or provider configuration.",
  "登录页面未能自动打开，请点击“打开登录页面”重试。": "The sign-in page did not open automatically. Click “Open sign-in page” to try again.",
  "已关闭输入窗口，仍可在浏览器完成登录。": "Input window closed. You can still finish signing in through the browser.",
  "授权结果输入窗口未能打开，可继续浏览器登录或重试输入。": "The authorization input window could not be opened. Continue in the browser or retry input.",
  "在登录页面输入此设备码": "Enter this device code on the sign-in page",
  "设备码": "Device code",
  "重新显示设备码": "Show device code again",
  "在浏览器完成授权后，这里会自动更新连接状态。": "The connection status updates automatically after browser authorization.",
  "模型": "Models",
  "自定义供应商": "Custom providers",
  "本机资源": "Local resources",
  "智能体档案": "Agent profiles",
  "外观": "Appearance",
  "工作台": "Workbench",
  "已归档任务": "Archived tasks",
  "自进化": "Self-evolution",
  "通知": "Notifications",
  "Host 诊断": "Host diagnostics",
  "关于 D Code": "About D Code",
  "设置分类": "Settings categories",
  "返回工作台": "Return to workbench",
  "能力": "Capabilities",
  "偏好": "Preferences",
  "应用": "Application",
  "运行服务已断开。": "Runtime service disconnected.",
  "关闭错误": "Dismiss error",
  "选择这台 Mac 上的显示方式。": "Choose how D Code appears on this Mac.",
  "显示与沟通语言": "Display and communication language",
  "界面、新生成的子会话标题和智能体回复使用所选语言。已有消息与名称保留原文。": "Applies to the interface, new child conversation titles, and Agent replies. Existing messages and names keep their original text.",
  "中文": "中文",
  "应用外观": "Appearance",
  "跟随系统，或固定使用浅色、深色。": "Follow the system or choose light or dark.",
  "系统": "System",
  "浅色": "Light",
  "深色": "Dark",
  "界面字号": "Text size",
  "整体调整文字和控件大小。": "Adjust text and control sizes together.",
  "紧凑": "Compact",
  "标准": "Standard",
  "大": "Large",
  "导航区、设置分类和对象详情共用已保存的栏宽。": "Navigation, settings categories, and object details use saved panel widths.",
  "进入任务时显示概览": "Show overview when opening a task",
  "导航区宽度": "Navigation width",
  "对象详情宽度": "Details panel width",
  "恢复默认布局": "Restore default layout",
  "恢复默认": "Restore defaults",
  "归档保留任务、会话和历史记录，可以随时恢复。": "Archiving keeps tasks, conversations, and history. Restore them at any time.",
  "导入 Pi 会话…": "Import Pi conversation…",
  "恢复任务": "Restore task",
  "没有已归档任务。": "No archived tasks.",
  "只在一次执行已确认结束时发送通知。": "Send notifications only when a run has confirmed completion.",
  "任务完成时通知我": "Notify me when a task completes",
  "通知只包含任务标题，不包含回答正文。": "Notifications contain the task title, without reply content.",
  "系统通知设置": "System notification settings",
  "提醒方式、声音与专注模式由 macOS 管理。": "macOS manages alerts, sounds, and Focus mode.",
  "打开系统设置": "Open System Settings",
  "正在保存工作台并切换应用…": "Saving the workbench and switching applications…",
  "选择对话使用的模型，并管理已有连接。": "Choose conversation models and manage connections.",
  "刷新目录": "Refresh catalog",
  "部分模型目录未能更新：": "Some model catalogs could not be refreshed: ",
  "。目录已保留，请检查对应连接状态。": ". The catalog is kept. Check the corresponding connection status.",
  "默认模型": "Default model",
  "用于新对话，可在输入区随时切换。": "Used for new conversations. Change it from the composer at any time.",
  "尚无可用连接。请在下方检查连接状态，再选择模型开始对话。": "No available connections. Check connection status below, then choose a model to start.",
  "连接模型": "Connect a model",
  "默认思考强度": "Default reasoning level",
  "用于新对话。可选范围随模型变化。": "Used for new conversations. Available levels depend on the model.",
  "自动选择的剩余额度门槛": "Minimum remaining quota for automatic selection",
  "剩余额度不高于此值时，沿原有回退顺序选择下一个模型。用于后续自动派发和回退，不中断正在执行的工作。": "When remaining quota is at or below this threshold, try the next model in the existing fallback order. Applies to future automatic dispatch and fallback; active work continues.",
  "模型连接": "Model connections",
  "{0} 个可用供应商 · {1} 个可选择模型": "{0} available providers · {1} selectable models",
  "管理自定义供应商": "Manage custom providers",
  "模型连接与目录": "Model connections and catalog",
  "正在获取最新目录": "Getting the latest catalog",
  "更新于 {0}": "Updated {0}",
  "已缓存的目录": "Cached catalog",
  "搜索模型目录": "Search model catalog",
  "仅看可用连接": "Available connections only",
  "启用全部模型": "Enable all models",
  "可用": "Available",
  "已保存，暂不可用": "Saved; temporarily unavailable",
  " 个模型": " models",
  "查看模型与启用范围": "View models and enabled scope",
  " · 上下文 {0}": " · Context {0}",
  " · 支持思考": " · Reasoning supported",
  "启用模型 {0}": "Enable model {0}",
  "没有找到匹配的模型。": "No matching models found.",
  "暂无已连接的模型，可管理供应商或查看全部目录。": "No connected models yet. Manage providers or view the full catalog.",
  "没有模型信息，请刷新目录。": "No model information. Refresh the catalog.",
  "自定义 API 地址和模型。保存后可在模型页连接，也可使用已有环境变量。": "Configure custom API endpoints and models. Connect from the Models page after saving, or use existing environment variables.",
  "新建供应商": "New provider",
  "删除": "Delete",
  "尚未添加自定义供应商。": "No custom providers added.",
  "既有自定义供应商": "Existing custom provider",
  "已配置认证": "Authentication configured",
  "未配置认证": "Authentication not configured",
  "编辑供应商": "Edit provider",
  "保存后由 D Code 管理这份供应商配置；既有认证继续引用，旧配置文件保持原样。": "D Code manages this provider configuration after saving. Existing credentials remain referenced; the old configuration file is kept.",
  "使用旧配置的认证引用": "Use the old configuration's credential reference",
  "保存后通过安全窗口连接密钥": "Connect a key through the secure window after saving",
  "供应商 ID": "Provider ID",
  "显示名称": "Display name",
  "API 地址": "API endpoint",
  "密钥所在环境变量": "Environment variable containing the key",
  "例如 MY_PROVIDER_API_KEY": "e.g. MY_PROVIDER_API_KEY",
  "API 协议": "API protocol",
  "模型 ID": "Model ID",
  "模型名称": "Model name",
  "上下文长度": "Context length",
  "最大输出": "Maximum output",
  "模型单独配置": "Model-specific configuration",
  "API 协议（可选）": "API protocol (optional)",
  "跟随供应商": "Follow provider",
  "API 地址（可选）": "API endpoint (optional)",
  "支持推理": "Supports reasoning",
  "删除模型 {0}": "Delete model {0}",
  "添加模型": "Add model",
  "高级兼容性参数": "Advanced compatibility parameters",
  "兼容性参数 JSON": "Compatibility parameters JSON",
  "保存供应商": "Save provider",
  "查看当前加载的扩展包、技能、提示模板与命令。": "View loaded extension packages, skills, prompt templates, and commands.",
  "重新加载": "Reload",
  "正在读取资源…": "Loading resources…",
  "扩展包来源 · ": "Extension package sources · ",
  "保留发现的资源来源。外部扩展代码不在当前任务中加载。": "Keep discovered resource sources. External extension code is not loaded in the current task.",
  "来源记录": "Source records",
  "没有配置扩展包。": "No extension packages configured.",
  "扩展": "Extensions",
  "技能": "Skills",
  "提示模板": "Prompt templates",
  "命令": "Commands",
  "启用{0} {1}": "Enable {0} {1}",
  "没有已加载的": "No loaded ",
  "加载诊断": "Loading diagnostics",
  "保存可复用的智能体职责与行为约定，已有运行保留启动时的档案快照。": "Save reusable Agent roles and behavior contracts. Existing runs keep the profile snapshot captured at startup.",
  "启用档案 {0}": "Enable profile {0}",
  "编辑档案": "Edit profile",
  "新建档案": "New profile",
  "名称": "Name",
  "职责约定": "Role contract",
  "保存档案": "Save profile",
  "查看运行服务、连接和应用诊断。": "View runtime services, connections, and application diagnostics.",
  "运行服务": "Runtime service",
  "应用版本": "Application version",
  "正在读取": "Loading",
  "版本 {0} · 修订 {1}": "Version {0} · Revision {1}",
  "重启运行服务": "Restart runtime service",
  "重新连接前先停止正在执行的任务。": "Stop active tasks before reconnecting.",
  "诊断记录": "Diagnostic records",
  "清空记录": "Clear records",
  "暂无诊断记录。": "No diagnostic records.",
  "验证与构建隔离候选，受控重启后恢复工作台，再由你验收或回滚。": "Verify and build an isolated candidate. Restore the workbench after a controlled restart, then accept or roll back.",
  "候选已恢复原工作台": "The candidate restored the original workbench",
  "确认可以继续工作后，记录本次人工验收。": "Confirm that you can continue, then record manual acceptance.",
  "确认可继续使用": "Confirm usable",
  "发现问题": "Report an issue",
  "回滚上一构建": "Roll back to previous build",
  "D Code 源码目录": "D Code source directory",
  "选择 D Code 项目文件夹": "Choose the D Code project folder",
  "选择…": "Choose…",
  "自动检查": "Automated checks",
  "运行 Host 和 Web 客户端的检查与测试。": "Run checks and tests for the Host and Web client.",
  "运行检查": "Run checks",
  "准备下一构建": "Prepare the next build",
  "生成独立的本地候选，不替换当前应用。": "Create a separate local candidate while keeping the current application.",
  "构建候选": "Build candidate",
  "正在执行": "Executing",
  "执行完成": "Execution completed",
  "需要处理": "Needs attention",
  "查看构建输出": "View build output",
  "在访达中查看": "Show in Finder",
  "重启到候选并恢复任务": "Restart into candidate and restore task",
  "自进化记录": "Self-evolution records",
  "已记录重启请求": "Restart request recorded",
  "原任务已恢复，待验收": "Original task restored; awaiting acceptance",
  "已人工验收": "Manually accepted",
  "已回滚": "Rolled back",
  "切换未完成，原应用仍在运行": "Switch incomplete; original application is still running",
  "需要恢复": "Recovery required",
  "事件记录": "Event records",
  "尚无 Web 客户端自进化记录。": "No Web client self-evolution records yet.",
  "版本 ": "Version ",
  "作者 GitHub": "Author on GitHub",
  "打开作者 GitHub": "Open author on GitHub",
  "项目 GitHub": "Project on GitHub",
  "打开项目 GitHub": "Open project on GitHub",
  "来源文件已不存在。": "The source file no longer exists.",
  "来源已变成链接，不能安全读取。": "The source is now a link and cannot be read safely.",
  "来源不再是普通文件。": "The source is no longer a regular file.",
  "当前文件超过安全读取上限。": "The file exceeds the safe read limit.",
  "来源目录当前不可读取。": "The source directory cannot currently be read.",
  "原运行目录当前不可读取。": "The original working directory cannot currently be read.",
  "来源已离开原登记目录。": "The source has left its registered directory.",
  "来源已离开原运行目录。": "The source has left the original working directory.",
  "读取时文件发生变化，请重试。": "The file changed while being read. Try again.",
  "来源文件当前不可读取。": "The source file cannot currently be read.",
  "来源含有敏感内容，未展示正文。": "The source contains sensitive information. Its content is hidden.",
  "来源不是可显示的 UTF-8 文本。": "The source is not displayable UTF-8 text.",
  "灵感版本标识与保存的摘要不一致。": "The idea version identity does not match the saved digest.",
  "正在核对来源版本…": "Checking the source version…",
  " · 当前节点已到第 {0} 版": " · The current idea is at version {0}",
  "已核对到任务选定版本的内容。": "Content confirmed for the version selected by this task.",
  "已核对到本次运行当时使用的内容。": "Content confirmed for the version used by this run.",
  "当前文件已变化；当时正文没有保存在回执中，不能显示为原版本。": "The current file has changed. The original content was not saved in the receipt and cannot be shown as the old version.",
  "当时正文当前不可恢复。{0}": "The original content cannot currently be recovered. {0}",
  "来源核对信息": "Source verification information",
  "来源详情": "Source details",
  "来源原文": "Original source text",
  "关闭来源详情": "Close source details",
  "规范文件会自动读取，未重复添加。": "Project rules are read automatically and were not added again.",
  "已保存，下次运行开始使用。": "Saved. Applies from the next run.",
  "返回资料选择": "Return to source selection",
  "下次运行的附加资料": "Additional sources for the next run",
  "当前目录的规范文件会自动读取。这里的修改从下次运行生效；已运行的来源记录保留原版本。": "Rules in the current directory are read automatically. Changes here apply from the next run; prior runs keep their original source records.",
  "查看此版本": "View this version",
  "移除资料 {0}": "Remove source {0}",
  "尚未添加额外资料。": "No additional sources yet.",
  "添加文件": "Add file",
  "处理中…": "Processing…",
  "保存选择": "Save selection",
  "运行依据": "Run sources",
  "任务开始后可以查看实际输入、工具和来源。": "View the actual input, tools, and sources after the task starts.",
  "选择运行": "Choose run",
  "选择运行依据": "Choose run sources",
  "对话": "Conversation",
  "未完成": "Incomplete",
  "处理中": "Processing",
  "开始时的模型": "Model at startup",
  "文件操作": "File access",
  "可修改文件": "Can modify files",
  "只读": "Read only",
  "开始时可用工具": "Tools available at startup",
  "提交原文": "Submitted original text",
  "正在读取…": "Loading…",
  "交给模型的输入": "Input sent to the model",
  "本轮中的补充输入 · ": "Additional input during this run · ",
  "用户补充": "User addition",
  "协调补充": "Coordinator addition",
  "生效内容": "Effective input",
  "任务工作摘要": "Task work summary",
  "本轮开始时采用第 ": "Version used at the start of this run: ",
  " · 来源身份 ": " · Source identity ",
  "本轮没有采用任务工作摘要。": "This run did not use a task work summary.",
  "这段对话曾有摘要准备失败，原始材料仍可回查。": "Summary preparation previously failed in this conversation. Original sources remain accessible.",
  "按需读取的来源": "Sources read on demand",
  "刷新来源": "Refresh sources",
  "来源记录未能载入：": "Could not load source records: ",
  "正在读取本轮来源…": "Loading sources for this run…",
  "当前载入的记录中尚无实际读取；检索候选不会列在这里。运行中如有新读取，可刷新查看。": "The loaded records contain no actual reads yet; search candidates are not included. Refresh when new reads occur during the run.",
  "任务历史消息": "Task message history",
  "任务工作项": "Task work items",
  "检查证据": "Verification evidence",
  "项目文件": "Project files",
  "全局灵感": "Global inspiration",
  "第 {0} 版 · ": "Version {0} · ",
  "查看原文": "View original text",
  "加载更多来源": "Load more sources",
  "实际模型调用": "Actual model calls",
  "这次运行未保存详细调用记录。": "Detailed call records were not saved for this run.",
  "已返回结果": "Result returned",
  "调用未完成": "Call incomplete",
  "正在调用": "Calling",
  " · 思考 {0}": " · Reasoning {0}",
  "用于整理上下文": "Used to organize context",
  "这次调用的可用工具 · ": "Tools for this call · ",
  "没有工具": "No tools",
  "文档来源": "Document sources",
  "与运行时内容一致": "Matches the content used by this run",
  "文件在运行后已变化；旧正文未保存": "File changed after the run; the old content was not saved",
  "当时正文当前不可恢复": "The original content cannot currently be recovered",
  "查看当时来源": "View the original source",
  "模板": "Template",
  "本轮没有额外文档或输入展开来源。": "No additional documents or expanded input sources for this run.",
  "本轮使用了已导入的历史资料，来源摘要：": "This run used imported history. Source digest: ",
  "未通过": "Did not pass",
  "已归档": "Archived",
  "当前状态": "Current status",
  "任务已在别处更新。当前编辑仍保留在这里；请核对最新目标后再修订。": "This task was updated elsewhere. Your edit is kept here. Check the latest goal before revising it.",
  "当前任务目标仅可查看，不能修订。": "The current task goal is view only and cannot be revised.",
  "目标需说明这项任务要达到的结果。": "Describe the result this task should achieve.",
  "验收条件最多填写 100 条。": "Enter at most 100 acceptance criteria.",
  "每条验收条件最多 2000 字。": "Each acceptance criterion may contain at most 2000 characters.",
  "目标已保存，但界面刷新失败：{0}。请重新读取，勿重复保存。": "Goal saved, but the interface could not refresh: {0}. Reload instead of saving again.",
  "目标已保存，但界面仍未刷新：{0}。请稍后重新读取。": "Goal saved, but the interface still has not refreshed: {0}. Reload shortly.",
  "任务目标": "Task goal",
  "新任务目标": "New task goal",
  "任务{0}，目标和历史版本可查看，当前不能修订。": "Task is {0}. The goal and previous versions can be viewed, but cannot currently be revised.",
  "修订后保留旧版本，后续路线需要重新核对。": "Revisions keep earlier versions. Check subsequent routes again.",
  "填写时暂存，首次发送时采用；消息原文仍按输入内容保存。": "Saved as a draft and used on first send. The submitted message retains its original text.",
  "收起": "Collapse",
  "短期结果": "Intended result",
  "这项任务完成时要得到什么？": "What should this task produce when finished?",
  "验收目的 ": "Acceptance criteria ",
  "每行一条": "One per line",
  "怎样判断结果可接受？": "How will you judge whether the result is acceptable?",
  "当前路线依据已变化，后续执行前需重新核对。": "The current route's basis has changed. Check it again before further execution.",
  "查看目标版本": "View goal versions",
  "正在读取版本…": "Loading versions…",
  "验收：": "Acceptance: ",
  "暂无可读版本。": "No readable versions.",
  "取消本次编辑": "Cancel this edit",
  "读取中…": "Loading…",
  "重新读取已保存目标": "Reload saved goal",
  "保存中…": "Saving…",
  "保存修订": "Save revision",
  "保存到草稿": "Save to draft",
  "路线待核查": "Route needs checking",
  "路线已采用": "Route adopted",
  "原路线已失效": "Original route invalidated",
  "探索已停止": "Exploration stopped",
  "可以实施": "Ready to implement",
  "需要修订": "Revision required",
  "发现关键缺陷": "Critical defect found",
  "依据不足": "Insufficient evidence",
  "路线记录暂不可读，请保留记录并检查来源。": "The route record cannot currently be read. Keep it and check the source.",
  "任务路线": "Task route",
  "路线状态待核对": "Route status unconfirmed",
  "有新输入，路线待核对": "New input received; route needs checking",
  "任务要求已变更，路线待复核": "Task requirements changed; route needs review",
  "还有用户新输入待协调者核对。": "New user input still needs the coordinator's review.",
  "采用：": "Adopted: ",
  "探索 ": "Exploration ",
  " 轮 · 候选 ": " rounds · Candidates ",
  " · 检查 ": " · Checks ",
  "查看候选与检查依据": "View candidates and check evidence",
  " 轮": " rounds",
  " · 已采用": " · Adopted",
  "依据：": "Basis: ",
  "关键假设：": "Key assumptions: ",
  "未列出": "Not specified",
  "可能失败：": "Potential failure: ",
  "验证动作：": "Verification action: ",
  "预计投入：": "Estimated effort: ",
  "依赖与完成路径：": "Dependencies and completion path: ",
  "候选提出时列出的后续工作：": "Subsequent work listed when this candidate was proposed: ",
  "修订自：": "Revised from: ",
  "来源暂不可读": "Source temporarily unreadable",
  "工具检查": "Tool check",
  "检查成功": "Check succeeded",
  "未确认成功": "Success unconfirmed",
  "证据暂不可读：{0}": "Evidence temporarily unreadable: {0}",
  "查看检查成员的对话": "View the checking member's conversation",
  "尚未检查": "Not checked yet",
  "查看路线变化": "View route changes",
  " · 上限调整为 ": " · Limits changed to ",
  " 轮、": " rounds, ",
  " 个候选、": " candidates, ",
  " 次检查": " checks",
  "待核对": "Unconfirmed",
  "请在当前任务中创建一轮工作流，并先形成可查看的阶段安排。": "Create a workflow run in the current task and first prepare a visible stage plan.",
  "要完成的结果：": "Intended result: ",
  "范围与限制：": "Scope and constraints: ",
  "操作已保存，但界面刷新失败：{0}。请重新读取，勿重复操作。": "Action saved, but the interface could not refresh: {0}. Reload instead of repeating it.",
  "任务已经建立，但本轮工作流尚未确认；已回到原任务，请核对后选择继续编辑。": "Task created, but this workflow run is unconfirmed. Returned to the original task; check before continuing to edit.",
  "重新读取后仍未确认本轮工作流已创建；表单保留，请先核对主对话的提交结果，避免重复创建。": "Reloading has not confirmed workflow creation. The form is kept. Check the main conversation's submission result before creating again.",
  "本次汇总运行已结束，但没有可核对的协调报告；请查看运行结果，再明确选择是否重新请求。": "The report run ended without a verifiable coordinator report. Check the results, then explicitly choose whether to request again.",
  "本次汇总请求已受理，报告仍在生成或保存；请等待并重新读取，不要再次提交。": "The report request was accepted and is still being generated or saved. Wait and reload instead of submitting again.",
  "重新读取后汇总报告仍未落盘；请先核对本轮运行状态，避免重复请求。": "The report has still not been saved after reloading. Check this run's state before requesting again.",
  "操作已保存，但界面仍未刷新：{0}。请稍后重新读取。": "Action saved, but the interface still has not refreshed: {0}. Reload shortly.",
  "提交结果待核对；请重新读取任务状态，确认后再决定下一步，勿重复创建。": "Submission result unconfirmed. Reload task state and check it before choosing the next step. Do not create again.",
  "本次工作流请求未提交；请核对输入与任务状态后重试。": "This workflow request was not submitted. Check the input and task state before retrying.",
  "提交结果待核对：{0}。请先重新读取。": "Submission result unconfirmed: {0}. Reload first.",
  "请核对本轮工作流各阶段的实际结果、独立检查与证据，形成有来源的整体报告；不要替我接受任务。": "Check the actual results, independent checks, and evidence for every stage of this workflow. Prepare an overall report with sources; do not accept the task on my behalf.",
  "汇总请求结果待核对；请重新读取当前运行状态，勿重复请求。": "Report request result unconfirmed. Reload the current run state instead of requesting again.",
  "汇总请求未提交；请核对阶段证据与当前运行状态。": "Report request not submitted. Check stage evidence and the current run state.",
  "任务工作流": "Task workflow",
  "任务内工作流": "Workflow within this task",
  "一轮工作流属于当前任务；阶段结果来自实际成员、工作项与验收证据。": "Each workflow run belongs to this task. Stage results come from actual members, work items, and verification evidence.",
  "重新读取工作流提交状态": "Reload workflow submission status",
  "已由你核对并选择重新编辑；再次提交前请确认主对话没有收到上一次请求。": "You checked the status and chose to edit again. Before resubmitting, confirm that the main conversation did not receive the previous request.",
  "我已核对，返回编辑": "I checked; return to editing",
  "返回正在运行的工作流": "Return to the active workflow",
  "本任务工作流": "This task's workflow",
  "正在读取安排…": "Loading the plan…",
  "待形成并开始": "Awaiting plan and start",
  "当前运行仍对应第 ": "The current run still uses version ",
  " 版；已保存第 ": ". Saved version ",
  " 版。继续前会核对版本与目标。": ". The version and goal will be checked before continuing.",
  "本任务已有另一轮工作流在运行；当前安排可查看，待那一轮收口后再开始。": "Another workflow run is active in this task. View this plan, then start after the other run finishes.",
  "限制：": "Constraints: ",
  "已通过工作项验收": "Work item verification passed",
  "成员处理中": "Member working",
  "受阻": "Blocked",
  "待处理": "Pending",
  "前置阶段：": "Prerequisite stages: ",
  " · 等待 {0} 完成": " · Waiting for {0} to finish",
  "成员报告 ": "Member reports ",
  " · 协调复核通过 ": " · Coordinator reviews passed ",
  " · 请核对阻塞或返工": " · Check blockers or rework",
  "协调者正在形成阶段；安排保存后才能开始。": "The coordinator is defining stages. Save the plan before starting.",
  "停止原因：": "Stop reason: ",
  "开始工作流": "Start workflow",
  "用户选择停止本轮工作流的后续推进": "The user chose to stop further progress on this workflow run",
  "停止后续推进": "Stop further work",
  "继续工作流": "Continue workflow",
  "按最新要求重新核对并汇总": "Review the latest requirements and summarize again",
  "请求协调者核对并汇总": "Ask the coordinator to check and summarize",
  "核对并完成工作流": "Check and complete workflow",
  "发起新一轮": "Start a new run",
  "工作流完成后，任务仍由你单独验收。停止不会撤销已完成的文件或外部操作。": "The task still requires your separate acceptance after the workflow finishes. Stopping does not undo completed file or external operations.",
  "完成时会再次核对最新要求、阶段验收与目标版本；若报告已过期，可在这里重新请求汇总。": "Completion checks the latest requirements, stage verification, and goal version again. If the report is outdated, request another summary here.",
  "阶段正在返工或未验收，原报告暂不能用于完成；待阶段重新通过后再请求汇总。": "Stages need rework or verification, so the previous report cannot complete the workflow. Request a summary after the stages pass again.",
  "要完成的结果": "Intended result",
  "这轮工作流最终要交付什么？": "What should this workflow run deliver?",
  "范围与限制 ": "Scope and constraints ",
  "目录、时间、验收或副作用边界": "Directory, time, acceptance, or side effect boundaries",
  "查看将提交给协调者的原文": "View the exact text to send to the coordinator",
  "工作流表单独立提交；普通输入框中的草稿和附件会继续保留。": "The workflow form submits separately. Draft text and attachments in the ordinary composer are kept.",
  "创建工作流": "Create workflow",
  "打开 {0}{1} 的对话": "Open the conversation for {0}{1}",
  "，编号 {0}": ", ID {0}",
  "查看报告": "View report",
  "查看验收": "View verification",
  "第 {0} 轮团队执行": "Team run {0}",
  "{0} 名协作成员": "{0} collaborating members",
  " 名成员": " members",
  "该轮没有已创建的成员。": "No members created for this run.",
  "本轮失败原因：": "Run failure reason: ",
  "尚未创建协作成员。协调者需要分工时，成员会显示在这里。": "No collaborating members yet. They appear here when the coordinator delegates work.",
  "历史执行轮 ": "Historical run ",
  "未关联执行轮的成员": "Members without an associated run",
  "未关联执行轮": "No associated run",
  "归属待核对": "Assignment unconfirmed",
  "任务验收：": "Task acceptance: ",
  "已接受": "Accepted",
  "请查看归档记录": "See archived records",
  "尚未接受": "Not accepted yet",
  "。成员结果与任务验收分别记录。": ". Member results and task acceptance are recorded separately.",
  "来源暂时无法读取：": "Source temporarily unreadable: ",
  "正在读取原始材料…": "Loading original sources…",
  "灵感第 {0} 版": "Idea version {0}",
  "来源": "Source",
  "这条消息属于已退出的历史对话路径，不能直接当作当前要求。": "This message belongs to a historical conversation path that is no longer active. It cannot directly represent current requirements.",
  "来源内容已经变化，当时的正文无法恢复。": "The source changed and its original content cannot be recovered.",
  "来源已不可读取。": "The source can no longer be read.",
  "原引用身份仍保留。": "The original reference identity is kept.",
  "查看所属对话": "View the source conversation",
  "来源身份": "Source identity",
  "符号链接不进入项目预览": "Symbolic links are excluded from project previews",
  "当前目录仅显示前 1000 项。": "Only the first 1000 entries are shown in this folder.",
  "预览随编辑更新": "Preview updates as you edit",
  "联网资源：": "Network resources: ",
  "本次允许": "Allowed for this preview",
  "已阻止": "Blocked",
  "恢复阻止": "Block again",
  "页面跳转或联网请求已被阻止。": "Navigation or network requests were blocked.",
  "正在读取文件…": "Loading file…",
  "文件不可用": "File unavailable",
  "未保存": "Unsaved",
  "行": "Line",
  "跳转到文件行": "Go to file line",
  "引用当前行": "Reference current line",
  "查看文件原文": "View original file",
  "预览文件": "Preview file",
  "保存": "Save",
  "请求第 ": "Requested line ",
  " 行，当前文件只有 ": "; this file has only ",
  " 行。": " lines.",
  "重新加载磁盘内容": "Reload from disk",
  "用当前编辑覆盖": "Overwrite with current edit",
  "文件编辑内容": "File editor",
  "文件原文": "Original file",
  "项目文件导航": "Project file navigation",
  "Git 改动": "Git changes",
  "刷新文件与改动": "Refresh files and changes",
  "当前分支": "Current branch",
  "有 ": "There are ",
  " 个受限路径未显示。": " restricted paths hidden.",
  "仅显示前 1000 项改动。": "Only the first 1000 changes are shown.",
  "没有可显示的改动。": "No changes to show.",
  "当前目录没有可用的 Git 仓库。": "No available Git repository in this directory.",
  "正在读取改动…": "Loading changes…",
  "正在读取差异…": "Loading differences…",
  "差异不可用": "Differences unavailable",
  "{0}{1}[{2}](<{3}>)（{4}）\n差异版本：{5}\n```diff\n{6}\n```\n": "{0}{1}[{2}](<{3}>) ({4})\nDifference version: {5}\n```diff\n{6}\n```\n",
  "暂存差异": "Staged differences",
  "工作区差异": "Working tree differences",
  "已保存审查范围；协调者暂未收到安排：{0}": "Review scope saved; the coordinator has not received the assignment yet: {0}",
  "审查已加入当前任务（{0}）。": "Review added to this task ({0}).",
  "查看工作区改动": "View working tree changes",
  "查看暂存改动": "View staged changes",
  "打开文件": "Open file",
  "\n（差异较长，仅引用开头部分）": "\n(The differences are long; only the beginning is referenced)",
  "引用差异": "Reference differences",
  "审查关联工作项": "Work item linked to review",
  "新建审查工作项": "New review work item",
  "发起审查": "Start review",
  "刷新差异": "Refresh differences",
  "文件差异": "File differences",
  "引用差异{0}侧第 {1} 行": "Reference {0} side, line {1}",
  "旧": "old",
  "新": "new",
  "新侧第 {0} 行": "New side, line {0}",
  "旧侧第 {0} 行": "Old side, line {0}",
  "这一侧没有改动。": "No changes on this side.",
  "文件内容": "File content",
  "工作区标签": "Workspace tabs",
  " · 暂存差异": " · Staged differences",
  " · 工作区差异": " · Working tree differences",
  " · 差异": " · Differences",
  "关闭文件 {0} · {1}": "Close file {0} · {1}",
  "关闭 {0} · {1}": "Close {0} · {1}",
  "选择项目文件或 Git 改动。": "Choose a project file or Git change.",
  "[data-composer], [aria-label=\"打开文件详情\"], .file-navigation button": "[data-composer], [aria-label=\"Open file details\"], .file-navigation button",
  "文件有未保存修改": "File has unsaved changes",
  " 有未保存修改": " has unsaved changes",
  "关闭前保存，或保留编辑内容继续处理。": "Save before closing, or keep editing.",
  "放弃更改": "Discard changes",
  "保存并关闭": "Save and close",
  "待发送": "Queued",
  "正在处理": "Processing",
  "已回复": "Replied",
  "已暂停": "Paused",
  "上次执行已中断": "Previous run interrupted",
  "成员交流与待发送消息": "Member exchanges and queued messages",
  "待处理的协作更新 · ": "Pending collaboration update · ",
  "可继续处理或取消这次更新。成员的成果和原始记录仍会保留。": "Continue or cancel this update. Member results and original records will be kept.",
  "{0}的更新": "Update from {0}",
  "成员要求更新": "Member request updated",
  "继续处理": "Continue processing",
  "暂停处理": "Pause processing",
  "取消协作更新": "Cancel collaboration update",
  "查看更新内容": "View update",
  "你 → ": "You → ",
  "交办 → ": "Assignment → ",
  "等待运行名额": "Waiting for a run slot",
  "等待目录可写": "Waiting for write access",
  "暂停消息": "Pause message",
  "继续发送": "Resume sending",
  "取消消息": "Cancel message",
  "编辑待发送消息": "Edit queued message",
  "提前发送": "Send earlier",
  "延后发送": "Send later",
  "修改待发送消息": "Edit queued message",
  "取消编辑": "Cancel edit",
  "保存，保持暂停": "Save and keep paused",
  "发送前已修改，原文仍保留在记录中": "Edited before sending; original text remains in the record",
  "{0}的回复": "Reply from {0}",
  "提问导航": "Question navigation",
  "共 {0} 条提问": "{0} questions in total",
  "第 {0} 条提问：{1}": "Question {0}: {1}",
  "上下方向键选择提问，回车或空格跳转；Home 和 End 选择首尾提问。": "Use arrow keys to select, Enter or Space to jump, and Home or End for the first or last question.",
  " 条提问 · 共 ": " questions · Total ",
  " 条": " entries",
  "暂无回答": "No reply yet",
  "执行失败": "Execution failed",
  "执行已中断": "Execution interrupted",
  "{0}，展开执行过程": "{0}; expand execution history",
  "打开来源文件": "Open source file",
  "工具调用：": "Tool call: ",
  " · 记录 ": " · Record ",
  "输入参数": "Input parameters",
  "未记录输入参数": "No input parameters recorded",
  "工具输出": "Tool output",
  "正在等待工具输出…": "Waiting for tool output…",
  "未记录文本输出": "No text output recorded",
  "工具输出图片": "Tool output image",
  "正在等待模型返回内容…": "Waiting for model content…",
  "本次回复没有可展示的思考或工具记录。": "No reasoning or tool records to show for this reply.",
  "图片预览": "Image preview",
  "关闭图片预览": "Close image preview",
  "已确认": "Confirmed",
  "阻塞与待核对": "Blockers and unconfirmed items",
  "下一步": "Next step",
  "上版摘要": "Previous summary",
  "本次修订": "This revision",
  "查看来源": "View source",
  "本对话采用的第 {0} 版摘要正文暂不可恢复": "Summary version {0} used by this conversation cannot currently be recovered",
  "正在读取本对话实际采用的摘要…": "Loading the summary actually used by this conversation…",
  "采用版本的身份仍保留在运行回执中；不会以任务最新版冒充当时正文。": "The version identity remains in the run receipt. The task's latest version cannot stand in for the original content.",
  "查看任务当前版本": "View task's current version",
  "任务工作摘要暂不可用": "Task work summary temporarily unavailable",
  "这段对话仍可依据原始消息和资料继续；本轮是否采用摘要可在“上下文与运行依据”查看。": "This conversation can continue using original messages and sources. Check “Context and run sources” to see whether this run used a summary.",
  "最近一次准备失败：": "Latest preparation failure: ",
  "本轮输入已满": "Input limit reached for this run",
  "生成未完成": "Generation incomplete",
  "本对话已采用的任务摘要": "Task summary used by this conversation",
  "任务当前摘要": "Task's current summary",
  "任务当前摘要是第 {0} 版；本对话运行时采用第 {1} 版。": "The task's current summary is version {0}; this conversation used version {1} when it ran.",
  "任务当前摘要与本对话回执的内容身份不同，不能当作当时采用版本。": "The current task summary differs from the content identity in this conversation's receipt and cannot replace that version.",
  "返回本对话采用版本": "Return to the version used by this conversation",
  "这段对话尚未在运行中采用摘要；下次续接会记录实际采用版本。": "This conversation has not used a summary in a run yet. The actual version will be recorded on next continuation.",
  "任务事实已有变化，这版摘要需要重新核对。运行时会重新生成，旧版仍可回查。": "Task facts changed. This summary needs checking and will be regenerated when the run starts. The old version remains accessible.",
  "最近一次续接未采用摘要；原始材料仍保留，请查看运行依据。": "The latest continuation did not use a summary. Original sources are kept; view run sources.",
  "每行一条，可留空": "One per line; may be empty",
  "暂无记录": "No records yet",
  "纠正摘要": "Correct summary",
  "历史版本": "Previous versions",
  "正在核对来源…": "Checking sources…",
  "摘要来源：{0}": "Summary source: {0}",
  "当时的正文已不可恢复；来源身份仍保留。": "The original content can no longer be recovered. Its source identity is kept.",
  "摘要历史版本": "Summary history",
  "修订记录": "Revision records",
  "用户修订": "User revision",
  "自动整理": "Automatic summary",
  "查看": "View",
  "任务摘要第 {0} 版": "Task summary version {0}",
  " 版的声明与来源": " statements and sources",
  "会话记录": "Conversation records",
  "你的消息": "Your message",
  "收到的工作安排": "Received assignment",
  "D Code 回答": "D Code reply",
  "来自主对话的安排": "Assignment from the main conversation",
  "放大预览 {0}": "Enlarge {0}",
  "消息图片": "Message image",
  "正在回复": "Replying",
  "引用到输入框": "Quote in composer",
  "保存到灵感": "Save to Inspiration",
  "编辑并从这里继续": "Edit and continue from here",
  "从这里继续": "Continue from here",
  "这是同一任务的历史对话。内容保留供回查，请回到当前主对话继续。": "This is a historical conversation in the same task. Content is kept for reference. Return to the current main conversation to continue.",
  "消息暂时无法读取。": "Messages are temporarily unreadable.",
  "正在读取消息…": "Loading messages…",
  "开始这项任务": "Start this task",
  "开始新任务": "Start a new task",
  "描述目标，D Code 会接手推进。": "Describe a goal. D Code will take it forward.",
  "回到最新消息": "Jump to latest message",
  "无法连接应用，请重新打开 D Code。": "Could not connect to the application. Reopen D Code.",
  "数据刚刚更新，请重试。输入内容已保留。": "Data was just updated. Try again. Your input is kept.",
  "模型暂不可用，请检查模型选择和供应商连接。输入内容已保留。": "Model temporarily unavailable. Check the model selection and provider connection. Your input is kept.",
  "任务刷新返回了较早的状态；请重新读取并核对刚才的操作": "Task refresh returned an earlier state. Reload and check the previous action.",
  "文字草稿已保存。还有旧格式图片未暂存，退出后需要重新添加。": "Text draft saved. Some old-format images are not stored yet and must be added again after quitting.",
  "本次执行未能完成，请查看运行记录后重试。": "This run did not complete. Review the run record before retrying.",
  "这个扩展需要终端界面，D Code 已阻止该交互。": "This extension requires a terminal interface. D Code blocked the interaction.",
  "扩展未能完成当前操作": "The extension could not complete the current action",
  "当前对话还有待发送消息或协作更新，请先在对话下方处理后，再从历史继续。": "This conversation has queued messages or collaboration updates. Resolve them below the conversation before continuing from history.",
  "这条消息尚未完成来源核对，请等待运行收尾后重试。": "The source of this message is not confirmed yet. Wait for the run to finish, then retry.",
  "上一项工作流提交仍待核对，请先重新读取状态，不要重复发送。": "The previous workflow submission is still unconfirmed. Reload its state before sending again.",
  "请回到任务主对话，再提交工作流请求。": "Return to the task's main conversation to submit a workflow request.",
  "正在查看历史路径，请选择一条消息的“从这里继续”。输入内容已保留。": "You are viewing a historical path. Choose “Continue from here” on a message. Your input is kept.",
  "查看附件：{0}": "View attachment: {0}",
  "当前没有可停止的运行。": "No active run to stop.",
  "无法获取 {0} 的本地路径，请从 Finder 拖入或通过附件菜单选择。": "Could not get the local path for {0}. Drag it from Finder or choose it from the attachment menu.",
  "图片需大于 0 字节且不超过 5 MB。": "Images must be larger than 0 bytes and no larger than 5 MB.",
  "{0} 读取失败，请重新添加。": "Could not read {0}. Add it again.",
  "{0} 读取已取消。": "Reading {0} was cancelled.",
  "粘贴图片.png": "pasted-image.png",
  "图片消息（{0} 张）": "Image message ({0} images)",
  "用户消息": "User message",
  "终端": "Terminal",
  "读取文件": "Read file",
  "写入文件": "Write file",
  "编辑文件": "Edit file",
  "搜索内容": "Search content",
  "查找文件": "Find file",
  "查看目录": "List directory",
  "协作安排": "Collaboration plan",
  "验收记录": "Verification records",
  "等待决定": "Awaiting decision",
  "任务验收": "Task acceptance",
  "工具": "Tool",
  "读取 {0}": "Read {0}",
  "编辑 {0}": "Edit {0}",
  "写入 {0}": "Write {0}",
  "搜索 {0}": "Search {0}",
  "查找 {0}": "Find {0}",
  "查看 {0}": "View {0}",
  "运行命令": "Run command",
  "失败，查看错误": "Failed; view error",
  "进展更新": "Progress update",
  "进展": "Progress",
  "正在生成回复…": "Generating reply…",
  "展开查看错误与执行记录": "Expand errors and execution records",
  "图像输出": "Image output",
  "最低": "Minimal",
  "低": "Low",
  "中等": "Medium",
  "高": "High",
  "更高": "Extra high",
  "最高": "Maximum",
  "协调者": "Coordinator",
  "统筹任务计划，分配工作，处理待办并汇总证据。任务是否通过验收，由你确认。": "Manage the task plan, delegate work, resolve pending items, and summarize evidence. You decide whether the task passes acceptance.",
  "探索者": "Explorer",
  "调查指定问题，区分事实与推断，提供发现和依据，保持在任务范围内。": "Investigate the assigned question, separate facts from inference, and provide findings with evidence within the task's scope.",
  "执行者": "Worker",
  "在指定工作区完成分配的改动，报告结果、失败原因和产物。": "Complete the assigned change in the given workspace and report results, failures, and artifacts.",
  "验证者": "Verifier",
  "独立核对验收条件并提交证据，不把其他智能体的结论直接当作验证结果。": "Independently check acceptance criteria and submit evidence. Do not treat another Agent's conclusion as a verified result.",
  "智能体": "Agent",
  "最近执行 {0}": "Latest run {0}",
  "待返工": "Awaiting rework",
  "待复验": "Awaiting recheck",
  "验收未通过": "Verification failed",
  "历史状态待核对": "Historical status unconfirmed",
  "执行结束": "Run ended",
  "需要复验": "Recheck needed",
  "独立验收通过，待复核": "Independent verification passed; awaiting review",
  "独立验收未通过，待复核": "Independent verification failed; awaiting review",
  "报告已保存，待独立验收": "Report saved; awaiting independent verification",
  "等待你的决定": "Awaiting your decision",
  "运行": "Run",
  "等待": "Wait",
  "执行失败或中断": "Execution failed or interrupted",
  "历史结果 · {0}": "Historical result · {0}",
  "一次最多添加 32 个附件。": "Add at most 32 attachments at a time.",
  "文件名太长，请缩短搜索词": "The filename is too long. Shorten the search term.",
  "项目服务暂不可用，请稍后再试": "Project service temporarily unavailable. Try again shortly.",
  "文字": "Text",
  "图片": "Image",
  "链接": "Link",
  "视频": "Video",
  "已有编辑草稿，请先保存或放弃。": "An edit draft already exists. Save or discard it first.",
  "灵感已保存。": "Idea saved.",
  "已引用到“{0}”，下次运行会使用第 {1} 版。": "Referenced in “{0}”. Version {1} will be used in the next run.",
  "基于灵感“{0}”继续推进。": "Continue based on the idea “{0}”.",
  "已创建任务“{0}”并引用灵感。": "Created task “{0}” with this idea referenced.",
  "连接操作已返回，页面刷新失败，请重新刷新连接状态。": "The connection operation returned, but the page could not refresh. Refresh connection status again.",
  "请先选择任务，再打开项目文件引用": "Choose a task before opening a project file reference",
  "这个文件有尚未保存的编辑；请先保存或关闭后再打开引用。": "This file has unsaved edits. Save or close it before opening the reference.",
  "请先选择任务，再打开本机文件引用": "Choose a task before opening a local file reference",
  "引用不在当前文件目录范围内": "The reference is outside the current file directory's scope",
  "文件 {0} 有未保存修改，请先保存或放弃。": "File {0} has unsaved changes. Save or discard them first.",
  "（未保存编辑）": "(unsaved edits)",
  "请先保存或关闭相关目录中尚未保存的文件，再更换目录": "Save or close unsaved files in the affected directories before changing folders",
  "产物不可用": "Artifact unavailable",
  "项目不可用": "Project unavailable",
  "任务不可用": "Task unavailable",
  "本次执行已停止。": "This run was stopped.",
  "本次执行失败，请重试。": "This run failed. Try again.",
  "工具已结束，无文本输出。": "Tool finished without text output.",
  "Host 已连接，协议握手完成": "Host connected; protocol handshake completed",
  "本次执行已完成": "This run completed",
  "可以查看执行结果。": "You can view the results.",
  "预览操作无效": "Invalid preview action",
  "运行服务尚未连接，请重新连接。": "Runtime service is not connected yet. Reconnect.",
  "恢复回执不存在": "Recovery receipt missing",
  "恢复应用身份不匹配": "Recovery application identity does not match",
  "启动确认文件不匹配": "Startup confirmation file does not match",
  "上一构建已启动，回滚记录需人工确认": "The previous build started; rollback records need manual confirmation",
  "当前不能切换应用": "Application switching is currently unavailable",
  "切换方式无效": "Invalid switching method",
  "界面未完成保存": "The interface has not finished saving",
  "候选路径无效": "Invalid candidate path",
  "选择任务附加资料": "Choose additional task sources",
  "文本与代码": "Text and code",
  "选择项目文件夹": "Choose project folder",
  "灵感预览暂不可用。": "Inspiration preview temporarily unavailable.",
  "附件预览暂不可用。": "Attachment preview temporarily unavailable.",
  "不支持打开此链接。": "This link cannot be opened.",
  "运行服务未连接": "Runtime service disconnected",
  "设置…": "Settings…",
  "隐藏 D Code": "Hide D Code",
  "退出 D Code": "Quit D Code",
  "新建项目…": "New project…",
  "关闭窗口": "Close window",
  "视图": "View",
  "进入全屏幕": "Enter Full Screen",
  "开发者工具": "Developer Tools",
  "完成通知": "Completion notifications",
  "通知偏好未能保存": "Notification preference could not be saved",
  "窗口": "Window",
  "界面没有及时完成保存。": "The interface did not finish saving in time.",
  "退出前还有内容需要处理": "Some content needs attention before quitting",
  "仍然退出": "Quit anyway",
  "候选不是 D Code Web 应用": "The candidate is not a D Code Web application",
  "候选的数据版本不同，需要先完成专门的数据迁移验证": "The candidate uses a different data version. Complete dedicated migration verification first.",
  "候选包含应用目录之外的文件引用": "The candidate references files outside its application directory",
  "候选进程尚未退出，原版本暂未重新连接，以免产生两个写入者": "The candidate process has not exited. The previous version has not reconnected, to keep a single writer.",
  "请从本地 .app 候选中进行切换": "Switch from a local .app candidate",
  "没有可回滚的上一构建": "No previous build available to roll back to",
  "请先成功构建候选": "Build a successful candidate first",
  "候选就是当前应用": "The candidate is the current application",
  "上一构建已经改变，不能按旧回执回滚": "The previous build changed. It cannot be restored using the old receipt.",
  "目标构建无法恢复附件草稿，请先发送或移除未发送的附件，再切换构建。": "The target build cannot restore attachment drafts. Send or remove unsent attachments before switching.",
  "候选启动后提前退出": "The candidate exited before startup finished",
  "候选无法恢复原会话": "The candidate could not restore the original conversation",
  "候选未确认恢复原任务": "The candidate did not confirm restoration of the original task",
  "旧服务尚未确认退出，已暂停切换，未启动其他写入者": "The old service has not confirmed exit. Switching is paused; another writer was not started.",
  "候选未完成启动确认，已返回原应用": "The candidate did not confirm startup. Returned to the original application.",
  "候选未能完成恢复，已返回原版本。": "The candidate could not complete recovery. Returned to the previous version.",
  "预览内容无效": "Invalid preview content",
  "预览服务尚未连接": "Preview service is not connected yet",
  "预览位置无效": "Invalid preview position",
  "预览已经改变": "The preview changed",
  "无法建立隔离预览": "Could not create an isolated preview",
  "正在准备": "Preparing",
  "正在生成图片": "Generating image",
  "图片已保存": "Image saved",
  "已取消生成": "Generation cancelled",
  "生成结果待核对": "Image result unconfirmed",
  "这台 Mac 尚未安装生图所需的 Codex 运行组件。": "The Codex runtime required for image generation is not installed on this Mac.",
  "当前 Codex 版本尚未通过 D Code 生图验证，暂不能使用。": "This Codex version has not passed D Code image verification and cannot be used yet.",
  "请先连接 Codex 的 ChatGPT 订阅账号。": "Connect a ChatGPT subscription account in Codex first.",
  "当前 Codex 使用 API Key；本入口只使用订阅账号，不会自动切换计费方式。": "Codex currently uses an API Key. This entry uses subscription accounts only and will not switch billing modes automatically.",
  "当前账号的图像能力不可用，请核对账号后重试。": "Image generation is unavailable for the current account. Check the account and try again.",
  "当前运行组件不能满足生图的工具隔离要求，入口暂不可用。": "The runtime cannot meet the required tool isolation. This entry is temporarily unavailable.",
  "本次适用用量不足，请稍后核对 Codex 账号用量。": "Insufficient applicable usage. Check Codex account usage later.",
  "本任务已有图片正在生成，请等待或停止后再发起。": "An image is already being generated in this task. Wait or stop it before starting another.",
  "请回到当前任务主对话使用图像能力。": "Return to the current task's main conversation to use image generation.",
  "当前任务不能新增图片，请创建或继续一个可工作的任务。": "The current task cannot add images. Create or continue an active task.",
  "描述中可能包含凭据，请移除后再提交。": "The description may contain credentials. Remove them before submitting.",
  "结果超过 5 MB 图像边界，未登记为成功产物。": "The result exceeds the 5 MB image limit and was not registered as a successful artifact.",
  "返回的图片无法完整解码，未登记为成功产物。": "The returned image could not be fully decoded and was not registered as a successful artifact.",
  "目标文件已经存在，请选择其他名称；原文件未被覆盖。": "The destination file exists. Choose another name; the original was not overwritten.",
  "导出未完成，原产物仍保留，请检查目标文件夹后重试。": "Export incomplete. The original artifact is kept. Check the destination folder and try again.",
  "受管图片或来源已变化，不能继续引用或导出。": "The managed image or its source changed. It cannot be referenced or exported.",
  "已停止等待，但无法确认服务是否已生成；不会自动重发。": "Stopped waiting, but the service result is unconfirmed. The request will not be sent again automatically.",
  "生图请求发出前运行服务已中断，可重新发起。": "The runtime stopped before the image request was sent. You may start a new request.",
  "提交给生图服务前已取消。": "Cancelled before submission to the image service.",
  "正在连接账号或生成图片，请稍后再操作。": "An account connection or image generation is in progress. Try again shortly.",
  "当前 Codex 账号计划不支持此图像能力，请更换适用订阅账号。": "This Codex account plan does not support image generation. Connect an eligible subscription account.",
  "当前账号的订阅资格尚未确认，不能开始生图。": "Subscription eligibility is unconfirmed. Image generation cannot start.",
  "图片结果尚未完成受管保存，请核对记录；不会自动重新生成。": "The result has not finished saving to managed storage. Check the record; it will not be generated again automatically.",
  "生图运行服务响应超时，请核对结果，不要重复发起。": "The image runtime timed out. Check the result instead of starting a duplicate request.",
  "所选导出位置不可写入，请选择普通文件夹。": "The export location is protected or unavailable. Choose an ordinary folder.",
  "导出目录的身份已变化，请重新选择位置。": "The destination folder's identity changed. Choose the location again.",
  "项目目录在导出期间已变化，请重新选择位置；原产物仍保留。": "The project folder changed during export. Choose the location again; the original artifact is kept.",
  "图片已收到，但运行未完整结束；只保留待核对图片，不登记为成功交付。": "An image was received, but the run did not finish. It is kept as an unconfirmed image, without registering a successful deliverable.",
  "图像操作未完成，请核对运行组件、账号或保存位置后重试。": "Image operation incomplete. Check the runtime, account, or save location before retrying.",
  "任务图像生成": "Task image generation",
  "生成图片": "Generate image",
  "试验": "Experimental",
  "关闭图像生成": "Close image generation",
  "只发送这次描述给 OpenAI，使用当前 Codex 订阅账号的适用用量。不会附带项目文件、任务历史或其他附件。本试验不能保证单次扣量，额度与实际消耗未知。": "Only this description is sent to OpenAI, using applicable usage from your current Codex subscription account. Project files, task history, and other attachments are excluded. This experiment cannot guarantee a single usage charge. Available quota and actual consumption are unknown.",
  "账号与运行前检查已通过": "Account and preflight checks passed",
  "提交前会核对账号与图像能力": "Account and image capability are checked before submission",
  "检查 Codex 账号": "Check Codex account",
  "等待浏览器登录…": "Waiting for browser sign-in…",
  "连接 Codex": "Connect Codex",
  "停止等待登录": "Stop waiting for sign-in",
  "图像记录暂时无法读取，当前列表不能代表完整历史。": "Image records are temporarily unreadable. The current list does not represent the full history.",
  "提交结果尚未核对。可先重新读取；重新提交沿用原请求身份，若请求尚未送达，将开始生成并消耗适用用量。": "Submission result unconfirmed. Reload first. Resubmitting keeps the original request identity; if it has not arrived, generation will begin and consume applicable usage.",
  "核对提交状态": "Check submission status",
  "描述一张你想生成的图片…": "Describe one image you want to generate…",
  "图像描述": "Image description",
  "当前普通消息草稿与附件会保留。App Server 属于试验能力。": "Your ordinary message draft and attachments are kept. App Server is experimental.",
  "正在处理图像请求…": "Processing image request…",
  "重新提交原请求": "Resubmit original request",
  "生成一张": "Generate one image",
  "本任务图像记录": "Images in this task",
  "中断或停止不代表没有生成，也不撤销已发生用量。本记录保留，不会在重启后自动重发。": "Interruption or stopping does not prove that no image was generated and does not undo usage. This record is kept and will not be sent again automatically after restart.",
  "预览生成图片": "Preview generated image",
  "用作输入附件": "Use as input attachment",
  "导出图片": "Export image",
  "停止等待生图": "Stop waiting for image",
  "重新核对记录": "Check record again",
  "查看已保存的待核对图片": "View saved unconfirmed image",
  "生成图片（试验）": "Generate image (experimental)",
  "导出生成图片": "Export generated image",
  "Codex 运行组件无法启动，请检查安装后再试。": "The Codex runtime could not start. Check its installation and try again.",
  "Codex 登录资料位置不符合隔离要求，请使用独立的 Codex 配置目录。": "The Codex sign-in location does not meet isolation requirements. Use a separate Codex configuration directory.",
  "当前运行环境无法打开 Codex 登录，请检查浏览器连接。": "Codex sign-in cannot open in this environment. Check the browser connection.",
  "Codex 登录未完成，请重新连接订阅账号。": "Codex sign-in did not finish. Reconnect your subscription account.",
  "已停止当前操作，请核对已有记录后再决定是否重新发起。": "The operation was stopped. Check existing records before deciding whether to start again.",
  "生图运行服务暂不可用，请检查 Codex 运行组件后再试。": "The image runtime is unavailable. Check the Codex runtime and try again.",
  "生图运行服务已退出，请先核对已有记录；未知结果不会自动重发。": "The image runtime exited. Check existing records first. Unconfirmed requests will not be sent again automatically.",
  "生图服务未完成请求，请核对记录与账号状态后再试。": "The image service did not complete the request. Check the record and account status before retrying.",
  "服务报告生成失败，请核对记录与账号用量后再决定是否新建请求。": "The service reported generation failure. Check the record and account usage before deciding whether to start a new request.",
  "等待生图结果超时，请重新核对记录；超时不代表没有消耗用量。": "Waiting for the image timed out. Check the record again; a timeout does not prove that no usage was consumed.",
  "本机图像校验组件无法运行，结果未登记为成功产物。": "Local image validation could not run. The result was not registered as a successful artifact.",
  "生图运行尝试了未授权能力，已停止；请核对结果与账号用量。": "The image run attempted an unauthorized capability and was stopped. Check the result and account usage.",
  "生图运行提出了未授权请求，已拒绝并停止。": "The image run made an unauthorized request. It was denied and the run was stopped.",
  "生图服务返回了无法核对的事件，结果未登记为成功产物。": "The image service returned an unverifiable event. The result was not registered as a successful artifact.",
  "服务尝试生成多张图片，已停止且未登记为单图成功；请核对账号用量。": "The service attempted multiple images and was stopped without registering single-image success. Check account usage.",
  "本次运行没有返回可核对的图片，请核对账号与图像记录。": "This run did not return a verifiable image. Check the account and image record.",
  "这条图像记录的来源或格式无效，不能继续引用。": "This image record has an invalid source or format and cannot be referenced.",
  "图像记录不存在，请重新读取当前任务的图像记录。": "The image record does not exist. Reload this task's image records.",
  "这条记录尚无已确认的成功图片，不能附为输入或导出。": "This record has no confirmed successful image to attach or export.",
};
