import {useEffect,useState} from 'react';
import {FilePlus,X} from 'lucide-react';
import {api,errorText} from '../types';
import type {Workbench} from '../useWorkbench';
import type {TaskContextSourceInput,PromptReceiptRecord} from '../../../../../host/src/product-store.js';
import type {DCodePromptSourceState} from '../../../../../host/src/prompt-source-status.js';
export function TaskContext({work}:{work:Workbench}){
  const task=work.task!;const current=work.snapshot!.taskContextSets.find(context=>context.taskId===task.id)!;
  const [sources,setSources]=useState<TaskContextSourceInput[]>(()=>current.sources.map(source=>({kind:source.kind,relativePath:source.relativePath,title:source.title,...(source.rootPath?{rootPath:source.rootPath}:{})})));const [baseRevision,setBaseRevision]=useState(current.revision),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const runs=work.snapshot!.sessionRuns.filter(run=>run.taskId===task.id);const [runId,setRunId]=useState(runs.at(-1)?.id??'');
  const selectedRun=runs.find(run=>run.id===runId);const environment=work.snapshot!.runtimeEnvironments.find(item=>item.id===selectedRun?.runtimeEnvironmentId);const tools=work.snapshot!.activeToolSets.find(item=>item.id===selectedRun?.activeToolSetId);
  const receipt=work.snapshot!.promptReceipts.find(item=>item.sessionRunId===runId) as (PromptReceiptRecord&{sourceStates?:DCodePromptSourceState[]})|undefined;
  const [inputs,setInputs]=useState<{rawText:string;effectiveText:string;additionalInputs?:Array<{author:string;text:string;effectiveText:string}>}|null>(null);
  useEffect(()=>{let alive=true;setInputs(null);if(runId)void api().request<NonNullable<typeof inputs>>('sessionRun.inputs',{taskId:task.id,sessionRunId:runId}).then(value=>{if(alive)setInputs(value);}).catch(error=>{if(alive)setError(errorText(error));});return()=>{alive=false;};},[task.id,runId]);
  const add=async()=>{setError('');try{const paths=await api().chooseContextFiles();if(!paths.length)return;setBusy(true);const result=await api().request<{sources:TaskContextSourceInput[];requiredAgents:boolean}>('task.context.inspectFiles',{taskId:task.id,paths});setSources(previous=>{const merged=[...previous];for(const source of result.sources)if(!merged.some(item=>item.kind===source.kind&&item.rootPath===source.rootPath&&item.relativePath===source.relativePath))merged.push(source);return merged;});if(result.requiredAgents)setNotice('规范文件会自动读取，未重复添加。');}catch(error){setError(errorText(error));}finally{setBusy(false);}};
  const save=async()=>{setBusy(true);setError('');try{const result=await work.mutateStore<{contextSet:{revision:number}}>('task.context.replace',{taskId:task.id,scope:task.scope,expectedContextRevision:baseRevision,sources});setBaseRevision(result.contextSet.revision);setNotice('已保存，下次运行开始使用。');await work.reload();}catch(error){setError(errorText(error));}finally{setBusy(false);}};
  return <div className="task-context-content"><h3>下次运行的附加资料</h3><p className="secondary">当前目录的规范文件会自动读取。这里的修改从下次运行生效；已运行的来源记录保留原版本。</p>
    <ul className="context-selection">{sources.map((source,index)=><li key={`${source.kind}:${source.rootPath??''}:${source.relativePath}`}><span><strong>{source.title??source.relativePath}</strong><small className="source-path">{source.rootPath?`${source.rootPath}/`:''}{source.relativePath}</small></span><button type="button" className="icon-button" disabled={busy} aria-label={`移除资料 ${source.title??source.relativePath}`} onClick={()=>setSources(items=>items.filter((_item,itemIndex)=>itemIndex!==index))}><X size={13}/></button></li>)}</ul>
    {sources.length===0&&<p className="secondary">尚未添加额外资料。</p>}
    <div className="form-actions"><button className="text-button" disabled={busy||sources.length>=31} onClick={()=>void add()}><FilePlus size={14}/>添加文件</button><span className="secondary">{sources.length} / 31</span><button className="primary-button" disabled={busy||sources.length>31} onClick={()=>void save()}>{busy?'处理中…':'保存选择'}</button></div>
    {error&&<p className="inline-error" role="alert">{error}</p>}{notice&&<p role="status" className="secondary">{notice}</p>}
    <h3>运行依据</h3>{!runs.length?<p className="secondary">任务开始后可以查看实际输入、工具和来源。</p>:<><label>选择运行<select aria-label="选择运行依据" value={runId} onChange={event=>setRunId(event.target.value)}>{runs.map((run,index)=><option key={run.id} value={run.id}>{work.snapshot!.sessions.find(session=>session.id===run.sessionId)?.title??'对话'} · 第 {index+1} 次 · {run.status==='completed'?'已完成':run.status==='failed'?'未完成':run.status==='aborted'?'已停止':run.status==='interrupted'?'已中断':'处理中'}</option>)}</select></label>
    {environment&&<dl className="receipt-facts"><dt>工作目录</dt><dd className="source-path">{environment.cwd}</dd><dt>开始时的模型</dt><dd>{environment.modelProvider} / {environment.modelId}</dd><dt>文件操作</dt><dd>{environment.workspaceAccess==='exclusiveWrite'?'可修改文件':'只读'}</dd></dl>}
    <details><summary>开始时可用工具</summary><ul>{(Array.isArray(tools?.tools)?tools.tools:[]).map((tool:{name:string;description:string})=><li key={tool.name}><strong>{tool.name}</strong><p className="secondary">{tool.description}</p></li>)}</ul></details>
    <details><summary>提交原文</summary><pre className="receipt-input">{inputs?.rawText??'正在读取…'}</pre></details><details><summary>交给模型的输入</summary><pre className="receipt-input">{inputs?.effectiveText??'正在读取…'}</pre></details>
    {!!inputs?.additionalInputs?.length&&<details><summary>本轮中的补充输入 · {inputs.additionalInputs.length}</summary>{inputs.additionalInputs.map((item,index)=><section key={index}><strong>{item.author==="user"?"用户补充":"协调补充"}</strong><pre className="receipt-input">{item.text}</pre><details><summary>生效内容</summary><pre className="receipt-input">{item.effectiveText}</pre></details></section>)}</details>}
    <h4>实际模型调用</h4>{!work.snapshot?.providerCalls?.some(call=>call.sessionRunId===runId)&&<p className="secondary">这次运行未保存详细调用记录。</p>}<ul className="receipt-sources">{work.snapshot?.providerCalls?.filter(call=>call.sessionRunId===runId).map(call=><li key={call.id}><strong>{call.providerId} / {call.modelId}</strong><span className="secondary">{call.state==="completed"?"已返回结果":call.state==="failed"?"调用未完成":"正在调用"}{call.httpStatus?` · HTTP ${call.httpStatus}`:""}{call.reasoning?` · 思考 ${call.reasoning}`:""}</span>{call.purpose==="context_summary"&&<span className="secondary">用于整理上下文</span>}{call.toolNames&&<details><summary>这次调用的可用工具 · {call.toolNames.length}</summary><p className="secondary">{call.toolNames.join("、")||"没有工具"}</p></details>}{call.error&&<span>{call.error}</span>}</li>)}</ul>
    <h4>文档来源</h4><ul className="receipt-sources">{receipt?.sourceReceipts.map(source=>{const state=receipt.sourceStates?.find(item=>item.path===source.path);return <li key={source.path}><strong>{source.title??source.path.split('/').at(-1)}</strong><small className="source-path">{source.path}</small><span className="secondary">{state?.state==='current_match'?'与运行时内容一致':state?.state==='hash_mismatch'?'文件在运行后已变化':'当前文件不可读取'}</span><code>{source.digest}</code></li>;})}{receipt?.inputSources?.map(source=><li key={source.path}><strong>{source.kind==='skill'?'技能':'模板'} · {source.name}</strong><small className="source-path">{source.path}</small><code>{source.digest}</code></li>)}</ul>{!receipt?.sourceReceipts.length&&!receipt?.inputSources?.length&&<p className="secondary">本轮没有额外文档或输入展开来源。</p>}
    {receipt?.importedHistoryReceipt&&<p className="secondary">本轮使用了已导入的历史资料，来源摘要：{receipt.importedHistoryReceipt.digest}</p>}
    </>}
  </div>;
}
