import { uiText } from "../../../shared/ui-language.ts";
import {useContext,useEffect,useRef,useState} from 'react';
import {FilePlus,X} from 'lucide-react';
import {api,errorText} from '../types';
import type {Workbench} from '../useWorkbench';
import type {TaskContextSourceInput,PromptReceiptRecord,TaskSourceSelector,TaskSourceUseRecord} from '../../../../../host/src/product-store.js';
import type {DCodePromptSourceState} from '../../../../../host/src/prompt-source-status.js';
import {SourceContent} from './SourceDetail';
import {TaskSourceReferenceContext} from './Markdown';
export function TaskContext({work}:{work:Workbench}){
  const openUsedSource=useContext(TaskSourceReferenceContext);
  const task=work.task!;const current=work.snapshot!.taskContextSets.find(context=>context.taskId===task.id)!;
  const [sources,setSources]=useState<TaskContextSourceInput[]>(()=>current.sources.map(source=>({kind:source.kind,relativePath:source.relativePath,title:source.title,...(source.rootPath?{rootPath:source.rootPath}:{})})));const [baseRevision,setBaseRevision]=useState(current.revision),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [inlineSource,setInlineSource]=useState<TaskSourceSelector|null>(null);
  const runs=work.snapshot!.sessionRuns.filter(run=>run.taskId===task.id);const [runId,setRunId]=useState(runs.at(-1)?.id??'');
  const runIdRef=useRef(runId);runIdRef.current=runId;
  const selectedRun=runs.find(run=>run.id===runId);const environment=work.snapshot!.runtimeEnvironments.find(item=>item.id===selectedRun?.runtimeEnvironmentId);const tools=work.snapshot!.activeToolSets.find(item=>item.id===selectedRun?.activeToolSetId);
  const receipt=work.snapshot!.promptReceipts.find(item=>item.sessionRunId===runId) as (PromptReceiptRecord&{sourceStates?:DCodePromptSourceState[]})|undefined;
  const [inputs,setInputs]=useState<{rawText:string;effectiveText:string;additionalInputs?:Array<{author:string;text:string;effectiveText:string}>}|null>(null);
  const [usedSources,setUsedSources]=useState<{items:TaskSourceUseRecord[];total:number;hasMore:boolean}|null>(null);
  const [usedError,setUsedError]=useState('');
  const usedLoadSerial=useRef(0);
  useEffect(()=>{let alive=true;setInputs(null);if(runId)void api().request<NonNullable<typeof inputs>>('sessionRun.inputs',{taskId:task.id,sessionRunId:runId}).then(value=>{if(alive)setInputs(value);}).catch(error=>{if(alive)setError(errorText(error));});return()=>{alive=false;};},[task.id,runId]);
  const loadUsedSources=async(requestedRunId:string,target:number)=>{const serial=++usedLoadSerial.current;setUsedError('');try{let items:TaskSourceUseRecord[]=[];let page:{items:TaskSourceUseRecord[];total:number;hasMore:boolean}|undefined;do{page=await api().request<NonNullable<typeof usedSources>>('task.source.used.list',{taskId:task.id,sessionRunId:requestedRunId,offset:items.length,limit:100});items=[...items,...page.items];}while(page.hasMore&&items.length<target);if(runIdRef.current===requestedRunId&&serial===usedLoadSerial.current)setUsedSources({items,total:page.total,hasMore:page.hasMore});}catch(reason){if(runIdRef.current===requestedRunId&&serial===usedLoadSerial.current)setUsedError(errorText(reason));}};
  useEffect(()=>{setUsedSources(null);if(runId)void loadUsedSources(runId,100);return()=>{usedLoadSerial.current++;};},[task.id,runId]);
  const moreUsedSources=async()=>{if(usedSources?.hasMore)await loadUsedSources(runId,usedSources.items.length+100);};
  const add=async()=>{setError('');try{const paths=await api().chooseContextFiles();if(!paths.length)return;setBusy(true);const result=await api().request<{sources:TaskContextSourceInput[];requiredAgents:boolean}>('task.context.inspectFiles',{taskId:task.id,paths});setSources(previous=>{const merged=[...previous];for(const source of result.sources)if(!merged.some(item=>item.kind===source.kind&&item.rootPath===source.rootPath&&item.relativePath===source.relativePath))merged.push(source);return merged;});if(result.requiredAgents)setNotice(uiText("规范文件会自动读取，未重复添加。"));}catch(error){setError(errorText(error));}finally{setBusy(false);}};
  const save=async()=>{setBusy(true);setError('');try{const result=await work.mutateStore<{contextSet:{revision:number}}>('task.context.replace',{taskId:task.id,scope:task.scope,expectedContextRevision:baseRevision,sources});setBaseRevision(result.contextSet.revision);setNotice(uiText("已保存，下次运行开始使用。"));await work.reload();}catch(error){setError(errorText(error));}finally{setBusy(false);}};
  if(inlineSource)return <div className="task-context-content"><button type="button" className="text-button" onClick={()=>setInlineSource(null)}>{uiText("返回资料选择")}</button><SourceContent selector={inlineSource}/></div>;
  return <div className="task-context-content"><h3>{uiText("下次运行的附加资料")}</h3><p className="secondary">{uiText("当前目录的规范文件会自动读取。这里的修改从下次运行生效；已运行的来源记录保留原版本。")}</p>
    <ul className="context-selection">{sources.map((source,index)=>{const saved=current.sources.find(item=>item.kind===source.kind&&item.rootPath===source.rootPath&&item.relativePath===source.relativePath);return <li key={`${source.kind}:${source.rootPath??''}:${source.relativePath}`}><span><strong>{source.title??source.relativePath}</strong><small className="source-path">{source.rootPath?`${source.rootPath}/`:''}{source.relativePath}</small></span>{saved?.inspirationVersion&&<button type="button" className="text-button" onClick={()=>setInlineSource({taskId:task.id,contextSourceId:saved.id})}>{uiText("查看此版本")}</button>}<button type="button" className="icon-button" disabled={busy} aria-label={uiText("移除资料 {0}", [source.title??source.relativePath])} onClick={()=>setSources(items=>items.filter((_item,itemIndex)=>itemIndex!==index))}><X size={13}/></button></li>;})}</ul>
    {sources.length===0&&<p className="secondary">{uiText("尚未添加额外资料。")}</p>}
    <div className="form-actions"><button className="text-button" disabled={busy||sources.length>=31} onClick={()=>void add()}><FilePlus size={14}/>{uiText("添加文件")}</button><span className="secondary">{sources.length} / 31</span><button className="primary-button" disabled={busy||sources.length>31} onClick={()=>void save()}>{busy?uiText("处理中…"):uiText("保存选择")}</button></div>
    {error&&<p className="inline-error" role="alert">{error}</p>}{notice&&<p role="status" className="secondary">{notice}</p>}
    <h3>{uiText("运行依据")}</h3>{!runs.length?<p className="secondary">{uiText("任务开始后可以查看实际输入、工具和来源。")}</p>:<><label>{uiText("选择运行")}<select aria-label={uiText("选择运行依据")} value={runId} onChange={event=>setRunId(event.target.value)}>{runs.map((run,index)=><option key={run.id} value={run.id}>{work.snapshot!.sessions.find(session=>session.id===run.sessionId)?.title??uiText("对话")} {uiText(" · 第 ")}{index+1} {uiText(" 次 · ")}{run.status==='completed'?uiText("已完成"):run.status==='failed'?uiText("未完成"):run.status==='aborted'?uiText("已停止"):run.status==='interrupted'?uiText("已中断"):uiText("处理中")}</option>)}</select></label>
    {environment&&<dl className="receipt-facts"><dt>{uiText("工作目录")}</dt><dd className="source-path">{environment.cwd}</dd><dt>{uiText("开始时的模型")}</dt><dd>{environment.modelProvider} / {environment.modelId}</dd><dt>{uiText("文件操作")}</dt><dd>{environment.workspaceAccess==='exclusiveWrite'?uiText("可修改文件"):uiText("只读")}</dd></dl>}
    <details><summary>{uiText("开始时可用工具")}</summary><ul>{(Array.isArray(tools?.tools)?tools.tools:[]).map((tool:{name:string;description:string})=><li key={tool.name}><strong>{tool.name}</strong><p className="secondary">{tool.description}</p></li>)}</ul></details>
    <details><summary>{uiText("提交原文")}</summary><pre className="receipt-input">{inputs?.rawText??uiText("正在读取…")}</pre></details><details><summary>{uiText("交给模型的输入")}</summary><pre className="receipt-input">{inputs?.effectiveText??uiText("正在读取…")}</pre></details>
    {!!inputs?.additionalInputs?.length&&<details><summary>{uiText("本轮中的补充输入 · ")}{inputs.additionalInputs.length}</summary>{inputs.additionalInputs.map((item,index)=><section key={index}><strong>{item.author==="user"?uiText("用户补充"):uiText("协调补充")}</strong><pre className="receipt-input">{item.text}</pre><details><summary>{uiText("生效内容")}</summary><pre className="receipt-input">{item.effectiveText}</pre></details></section>)}</details>}
    <h4>{uiText("任务工作摘要")}</h4>{receipt?.taskSummary?<p className="secondary">{uiText("本轮开始时采用第 ")}{receipt.taskSummary.revision} {uiText(" 版 · ")}{new Date(receipt.taskSummary.createdAt).toLocaleString('zh-CN')} {uiText(" · 来源身份 ")}{receipt.taskSummary.digest}</p>:<p className="secondary">{uiText("本轮没有采用任务工作摘要。")}{work.snapshot?.taskSummaryFailures.some(item=>item.sessionId===selectedRun?.sessionId)?uiText("这段对话曾有摘要准备失败，原始材料仍可回查。"):''}</p>}
    <h4>{uiText("按需读取的来源")}</h4><button className="text-button" onClick={()=>void loadUsedSources(runId,Math.max(100,(usedSources?.items.length??0)+1))}>{uiText("刷新来源")}</button>{usedError&&<p role="alert" className="inline-error">{uiText("来源记录未能载入：")}{usedError}</p>}{!usedSources&&!usedError&&<p className="secondary">{uiText("正在读取本轮来源…")}</p>}{usedSources?.total===0&&<p className="secondary">{uiText("当前载入的记录中尚无实际读取；检索候选不会列在这里。运行中如有新读取，可刷新查看。")}</p>}<ul className="receipt-sources">{usedSources?.items.map(use=><li key={use.id}><strong>{({task_message:uiText("任务历史消息"),work_item:uiText("任务工作项"),agent_report:uiText("成员报告"),evidence:uiText("检查证据"),project_file:uiText("项目文件"),inspiration:uiText("全局灵感")} as Record<string,string>)[use.kind]}</strong><span className="secondary">{use.kind==='inspiration'?uiText("第 {0} 版 · ", [use.version]):''}{use.sourceId}</span>{openUsedSource&&<button className="text-button" onClick={()=>openUsedSource(use.id)}>{uiText("查看原文")}</button>}</li>)}</ul>{usedSources?.hasMore&&<button className="text-button" onClick={()=>void moreUsedSources()}>{uiText("加载更多来源")}</button>}
    <h4>{uiText("实际模型调用")}</h4>{!work.snapshot?.providerCalls?.some(call=>call.sessionRunId===runId)&&<p className="secondary">{uiText("这次运行未保存详细调用记录。")}</p>}<ul className="receipt-sources">{work.snapshot?.providerCalls?.filter(call=>call.sessionRunId===runId).map(call=><li key={call.id}><strong>{call.providerId} / {call.modelId}</strong><span className="secondary">{call.state==="completed"?uiText("已返回结果"):call.state==="failed"?uiText("调用未完成"):uiText("正在调用")}{call.httpStatus?` · HTTP ${call.httpStatus}`:""}{call.reasoning?uiText(" · 思考 {0}", [call.reasoning]):""}</span>{call.purpose==="context_summary"&&<span className="secondary">{uiText("用于整理上下文")}</span>}{call.toolNames&&<details><summary>{uiText("这次调用的可用工具 · ")}{call.toolNames.length}</summary><p className="secondary">{call.toolNames.join("、")||uiText("没有工具")}</p></details>}{call.error&&<span>{call.error}</span>}</li>)}</ul>
    <h4>{uiText("文档来源")}</h4><ul className="receipt-sources">{receipt?.sourceReceipts.map((source,index)=>{const state=receipt.sourceStates?.find(item=>item.path===source.path);return <li key={`${source.path}:${index}`}><strong>{source.title??source.path.split('/').at(-1)}</strong><small className="source-path">{source.path}</small><span className="secondary">{state?.state==='current_match'?uiText("与运行时内容一致"):state?.state==='hash_mismatch'?uiText("文件在运行后已变化；旧正文未保存"):uiText("当时正文当前不可恢复")}</span><code>{source.digest}</code><button type="button" className="text-button" onClick={()=>setInlineSource({taskId:task.id,promptReceiptId:receipt.id,sourceIndex:index})}>{uiText("查看当时来源")}</button></li>;})}{receipt?.inputSources?.map(source=><li key={source.path}><strong>{source.kind==='skill'?uiText("技能"):uiText("模板")} · {source.name}</strong><small className="source-path">{source.path}</small><code>{source.digest}</code></li>)}</ul>{!receipt?.sourceReceipts.length&&!receipt?.inputSources?.length&&<p className="secondary">{uiText("本轮没有额外文档或输入展开来源。")}</p>}
    {receipt?.importedHistoryReceipt&&<p className="secondary">{uiText("本轮使用了已导入的历史资料，来源摘要：")}{receipt.importedHistoryReceipt.digest}</p>}
    </>}
  </div>;
}
