import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {PiHost} from '../src/pi-host.js';
import type {FoundationSnapshot,TaskBundle} from '../src/product-store.js';
const until=async(check:()=>Promise<boolean>,label:string)=>{const deadline=Date.now()+12000;while(!await check()){if(Date.now()>deadline)throw new Error(label);await new Promise(resolve=>setTimeout(resolve,30));}};
const exists=(pid:number)=>{try{process.kill(pid,0);return true;}catch{return false;}};
const response=(text:string,command?:string)=>new Response(`data: ${JSON.stringify({id:'fixture',object:'chat.completion.chunk',created:1,model:'fixture',choices:[{index:0,delta:command?{role:'assistant',tool_calls:[{index:0,id:'service',type:'function',function:{name:'bash',arguments:JSON.stringify({command})}}]}:{role:'assistant',content:text},finish_reason:null}]})}\n\ndata: ${JSON.stringify({id:'fixture',object:'chat.completion.chunk',choices:[{index:0,delta:{},finish_reason:command?'tool_calls':'stop'}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}})}\n\ndata: [DONE]\n\n`,{headers:{'content-type':'text/event-stream'}});

test('native auxiliary ownership survives main-process idle retirement, protects writes, and exposes bounded stop',async()=>{
  const root=await mkdtemp(join(tmpdir(),'dcode-native-aux-')),agent=join(root,'agent'),home=join(root,'home');await mkdir(agent);await mkdir(home);await writeFile(join(home,'note.md'),'原文');
  await writeFile(join(agent,'settings.json'),JSON.stringify({defaultProvider:'zai-coding-cn',defaultModel:'fixture'}));await writeFile(join(agent,'models.json'),JSON.stringify({providers:{'zai-coding-cn':{baseUrl:'https://open.bigmodel.cn/api/paas/v4',api:'openai-completions',apiKey:'fixture-only',models:[{id:'fixture',name:'Fixture',reasoning:false,input:['text'],contextWindow:100000,maxTokens:4096}]}}}));
  const previous=globalThis.fetch;let calls=0;globalThis.fetch=(async(url,init)=>{if(String(url).includes('quota/limit'))return Response.json({success:true,code:200,data:{limits:[{type:'TOKENS_LIMIT',percentage:10,nextResetTime:Date.now()+3600000}]}});calls++;const body=JSON.parse(String(init?.body));assert.ok(body.tools.some((item:any)=>item.function.name==='write'),'custom bash does not remove the existing file tools');return calls===1?response('','sleep 60 > /dev/null 2>&1 & echo $! > service.pid'):response('后台活动仍归当前成员，可以继续沟通。');}) as typeof fetch;
  const errors:unknown[]=[];const host=new PiHost({agentDir:agent,sessionsDirectory:join(agent,'sessions'),dataRoot:join(root,'.dcode'),userHome:home,agentIdleTimeoutMs:100,emit:(event,data)=>{if(/failed|error/iu.test(event))errors.push({event,data});}}),snapshot=()=>host.handle('foundation.snapshot',{}) as Promise<FoundationSnapshot>;let servicePid=0;
  try{
    await host.start();let snap=await snapshot();const task=await host.handle('task.create',{requestId:'task',expectedStoreRevision:snap.storeRevision,scope:{kind:'user',userId:snap.currentUser.id},title:'运行后台服务',goal:'归属、回收和继续沟通'}) as TaskBundle;
    await host.handle('dcodeSession.prompt',{dcodeSessionId:task.coordinationSession.id,promptId:'start',message:'启动后台活动并保留归属'});await until(async()=>(await snapshot()).auxiliaryProcesses?.some(item=>item.process.status==='background')??false,'service is durably owned');await until(async()=>(await snapshot()).agentProcesses?.some(item=>item.process.status==='exited'&&item.process.exitReason==='idle')??false,'main process retires while service remains owned');
    snap=await snapshot();const auxiliary=snap.auxiliaryProcesses![0]!,firstPid=snap.agentProcesses![0]!.process.pid;servicePid=Number(await readFile(join(home,'service.pid'),'utf8'));assert.ok(exists(servicePid));assert.equal(auxiliary.agentRunId,snap.agentRuns.find(run=>run.role==='coordinator')!.id);assert.ok(auxiliary.process.memberPids.includes(servicePid));
    const file=await host.handle('workspace.read',{source:{taskId:task.task.id},path:'note.md'}) as {digest:string;root:string};await assert.rejects(host.handle('workspace.save',{source:{taskId:task.task.id},path:'note.md',text:'不能与服务并发写',expectedDigest:file.digest,expectedRoot:file.root}),error=>(error as {code:string}).code==="WORKSPACE_IN_USE");
    await host.handle('dcodeSession.prompt',{dcodeSessionId:task.coordinationSession.id,promptId:'continue',message:'继续沟通，保留后台活动'});await until(async()=>(await snapshot()).sessionRuns.length===2&&!(await snapshot()).sessionRuns.some(run=>run.status==='running'),'fresh main process continues');snap=await snapshot();assert.ok(snap.agentProcesses!.some(item=>item.process.pid!==firstPid));assert.ok(exists(servicePid));assert.equal(snap.agentRuns.length,1,'new process is not a new member');
    await assert.rejects(host.handle('agentProcess.stopAuxiliary',{taskId:task.task.id,agentRunId:'wrong-agent',processId:auxiliary.process.id}),/不属于/);
    await host.handle('agentProcess.stopAuxiliary',{taskId:task.task.id,agentRunId:auxiliary.agentRunId,processId:auxiliary.process.id});await until(async()=>!exists(servicePid),'target service stopped');assert.equal((await snapshot()).auxiliaryProcesses![0]!.process.status,'exited');
    await host.handle('session.close',{runtimeId:snap.sessionRuns[0]!.runtimeId});const saved=await host.handle('workspace.save',{source:{taskId:task.task.id},path:'note.md',text:'停止后可保存',expectedDigest:file.digest,expectedRoot:file.root});assert.ok(saved);
  }catch(error){console.error(JSON.stringify({calls,errors,snapshot:await snapshot()},null,2));throw error;}finally{await host.close();globalThis.fetch=previous;if(servicePid)assert.ok(!exists(servicePid));await rm(root,{recursive:true,force:true});}
});
