import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {PiHost} from '../src/pi-host.js';
import type {ProductStore,FoundationSnapshot,TaskBundle} from '../src/product-store.js';
const until=async(check:()=>Promise<boolean>,label:string)=>{const deadline=Date.now()+20000;while(!await check()){if(Date.now()>deadline)throw new Error(label);await new Promise(resolve=>setTimeout(resolve,30));}};
function answer(text:string,action?:unknown,id=crypto.randomUUID(),toolName='dcode_team'){return new Response(`data: ${JSON.stringify({id:'fixture',object:'chat.completion.chunk',created:1,model:'fixture',choices:[{index:0,delta:action?{role:'assistant',tool_calls:[{index:0,id,type:'function',function:{name:toolName,arguments:JSON.stringify(action)}}]}:{role:'assistant',content:text},finish_reason:null}]})}\n\ndata: ${JSON.stringify({id:'fixture',object:'chat.completion.chunk',choices:[{index:0,delta:{},finish_reason:action?'tool_calls':'stop'}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}})}\n\ndata: [DONE]\n\n`,{headers:{'content-type':'text/event-stream'}});}
async function fixture(fetcher:(body:any)=>Promise<Response>){
  const root=await mkdtemp(join(tmpdir(),'dcode-dispatch-recovery-')),agent=join(root,'agent'),home=join(root,'home');await mkdir(agent);await mkdir(home);await writeFile(join(agent,'settings.json'),JSON.stringify({defaultProvider:'zai-coding-cn',defaultModel:'fixture',retry:{enabled:false}}));await writeFile(join(agent,'models.json'),JSON.stringify({providers:{'zai-coding-cn':{baseUrl:'https://open.bigmodel.cn/api/paas/v4',api:'openai-completions',apiKey:'fixture-only',models:[{id:'fixture',name:'Fixture',reasoning:false,input:['text'],contextWindow:200000,maxTokens:4096}]}}}));
  const previous=globalThis.fetch;globalThis.fetch=(async(url,init)=>String(url).includes('quota/limit')?Response.json({success:true,code:200,data:{limits:[{type:'TOKENS_LIMIT',percentage:10,nextResetTime:Date.now()+3600000}]}}):fetcher(JSON.parse(String(init?.body)))) as typeof fetch;
  const errors:unknown[]=[];const options={agentDir:agent,sessionsDirectory:join(agent,'sessions'),dataRoot:join(root,'.dcode'),userHome:home,emit:(event:string,data:unknown)=>{if(/failed|error/iu.test(event))errors.push({event,data});}};let host=new PiHost(options);const snapshot=()=>host.handle('foundation.snapshot',{}) as Promise<FoundationSnapshot>;await host.start();const snap=await snapshot(),task=await host.handle('task.create',{requestId:'task',expectedStoreRevision:snap.storeRevision,scope:{kind:'user',userId:snap.currentUser.id},title:'按需成员恢复',goal:'保留身份和等待原因'}) as TaskBundle;
  return {get host(){return host;},root,home,task,snapshot,errors,restart:async()=>{await host.close();host=new PiHost(options);await host.start();},close:async()=>{await host.close();globalThis.fetch=previous;await rm(root,{recursive:true,force:true});}};
}

test('members beyond the runtime limit wait durably and start after capacity is released',async()=>{
  let release!:()=>void;const held=new Promise<void>(resolve=>{release=resolve;});let mainCalls=0,memberCalls=0,stopMemberId="";
  const f=await fixture(async body=>{if(body.messages.find((message:any)=>message.role==='system').content.includes('coordinator Agent')){mainCalls++;if(mainCalls<=2)return answer('',{action:'delegate',members:Array.from({length:mainCalls===1?8:7},(_,index)=>({profileId:'builtin-explore',title:`成员 ${mainCalls}-${index}`,instruction:'独立核对已分配材料并返回',acceptance:'报告检查结果'}))});if(mainCalls===4&&stopMemberId)return answer('',{action:'stop',agentRunId:stopMemberId});return answer('可继续沟通，等待中的工作会在名额释放后开始');}memberCalls++;await held;return answer('独立工作已完成');});
  try{
    await f.host.handle('dcodeSession.prompt',{dcodeSessionId:f.task.coordinationSession.id,promptId:'start',message:'分批安排十五个独立工作项'});
    await until(async()=>(await f.snapshot()).agentRuns.length===16&&(await f.snapshot()).collaborationMessages?.filter(message=>message.waitingFor==='capacity').length===4,'four members visibly await capacity');await until(async()=>memberCalls===11,'the reserved member runtimes finish opening');assert.equal(memberCalls,11);
    const live=await f.host.handle('runtime.list',{}) as {runtimes:unknown[]};assert.equal(live.runtimes.length,12);const queued=(await f.snapshot()).collaborationMessages!.filter(message=>message.waitingFor==='capacity');assert.ok(queued.every(message=>message.state==='queued'));const waitingSnapshot=await f.snapshot();assert.ok(queued.every(message=>!waitingSnapshot.agentProcesses?.some(process=>process.agentRunId===message.targetAgentRunId)),'queued members have no invented execution process');
    stopMemberId=queued[0]!.targetAgentRunId;await until(async()=>!(await f.snapshot()).sessionRuns.some(run=>run.sessionId===f.task.coordinationSession.id&&run.status==='running'),'coordinator remains available');await f.host.handle('dcodeSession.prompt',{dcodeSessionId:f.task.coordinationSession.id,promptId:'pause-one',message:'先停止其中一个尚未启动的成员'});await until(async()=>(await f.snapshot()).collaborationMessages?.find(message=>message.id===queued[0]!.id)?.state==='paused','coordinator can stop a member before it has a runtime');
    release();await until(async()=>(await f.snapshot()).collaborationMessages?.filter(message=>message.author==='coordinator'&&message.state==='completed').length===14,'stopped member does not silently start when capacity returns');assert.equal(memberCalls,14);const paused=(await f.snapshot()).collaborationMessages!.find(message=>message.id===queued[0]!.id)!;await f.host.handle('collaboration.messageControl',{requestId:'resume-stopped-member',id:paused.id,expectedRevision:paused.revision,state:'queued'});

    release();await until(async()=>(await f.snapshot()).collaborationMessages?.filter(message=>message.author==='coordinator'&&message.state==='completed').length===15,'every scheduled member completes without recreation');await until(async()=>!(await f.snapshot()).collaborationMessages?.some(message=>['queued','delivering'].includes(message.state)),'results settle');assert.equal(memberCalls,15);assert.equal((await f.snapshot()).agentRuns.length,16);
  }catch(error){console.error(JSON.stringify({mainCalls,memberCalls,errors:f.errors,snapshot:await f.snapshot()},null,2));throw error;}finally{release();await f.close();}
});

test('a crash gap between member creation and initial message persistence recovers the same member paused',async()=>{
  let mainCalls=0,memberCalls=0;const f=await fixture(async body=>{if(body.messages.find((message:any)=>message.role==='system').content.includes('coordinator Agent')){mainCalls++;if(mainCalls===1)return answer('',{action:'delegate',members:[{profileId:'builtin-explore',title:'保留成员',instruction:'读取已确定的工作说明',acceptance:'返回结果'}]});return answer('成员已创建，待恢复未发出的说明');}memberCalls++;return answer('已经从原工作说明继续');});
  try{
    const store=(f.host as unknown as {productStore:ProductStore}).productStore,queue=store.queueCollaborationMessage.bind(store);let failed=false;store.queueCollaborationMessage=async input=>{if(!failed&&input.requestId.startsWith('delegate-initial:')){failed=true;throw new Error('fixture: interrupted before assignment persistence');}return queue(input);};
    await f.host.handle('dcodeSession.prompt',{dcodeSessionId:f.task.coordinationSession.id,promptId:'start',message:'安排一项持续工作'});await until(async()=>failed&&(await f.snapshot()).sessionRuns[0]?.status==='completed','creation gap reached');let snap=await f.snapshot();assert.equal(snap.agentRuns.length,2);assert.equal(memberCalls,0);assert.equal(snap.collaborationMessages!.length,0);const member=snap.agentRuns.find(run=>run.role==='explore')!;
    await f.restart();snap=await f.snapshot();assert.equal(snap.agentRuns.length,2);const restored=snap.collaborationMessages!.find(message=>message.targetAgentRunId===member.id)!;assert.equal(restored.state,'paused');assert.ok(restored.text.includes('读取已确定的工作说明'));assert.equal(memberCalls,0,'restart does not replay work automatically');
    await f.host.handle('collaboration.messageEdit',{requestId:'edit-initial',id:restored.id,expectedRevision:restored.revision,text:'编辑后的独立工作说明'});await f.restart();snap=await f.snapshot();assert.equal(snap.collaborationMessages!.length,1,'edited initial message is never recreated');const edited=snap.collaborationMessages![0]!;assert.equal(edited.text,'编辑后的独立工作说明');assert.equal(edited.state,'paused');

    await f.host.handle('collaboration.messageControl',{requestId:'resume',id:edited.id,expectedRevision:edited.revision,state:'queued'});await until(async()=>(await f.snapshot()).collaborationMessages?.some(message=>message.id===restored.id&&message.state==='completed')??false,'same member resumed');await until(async()=>!(await f.snapshot()).collaborationMessages?.some(message=>['queued','delivering'].includes(message.state)),'result notification settles');assert.equal(memberCalls,1);assert.equal((await f.snapshot()).agentRuns.length,2);
  }catch(error){console.error(JSON.stringify({mainCalls,memberCalls,errors:f.errors,snapshot:await f.snapshot()},null,2));throw error;}finally{await f.close();}
});

test('a created worktree whose ready receipt was interrupted is verified and recovered for the same member',async()=>{
  let coordinatorCalls=0,workerCalls=0;const f=await fixture(async body=>{
    if(body.messages.find((message:any)=>message.role==='system').content.includes('coordinator Agent')){coordinatorCalls++;if(coordinatorCalls===1)return answer('',{action:'delegate',members:[{profileId:'builtin-worker',title:'目录恢复成员',instruction:'检查原工作目录并返回',acceptance:'目录身份保持一致'}]});return answer('保留成员，按暂停原因恢复目录');}
    workerCalls++;assert.ok(body.tools.some((tool:any)=>tool.function.name==='bash'));return workerCalls===1?answer('',{path:'worker-result.md',content:'在原工作树完成写入'},crypto.randomUUID(),'write'):answer('已从原目录继续，没有另建成员或工作树');
  });
  try{
    const repo=join(f.home,'project');await mkdir(repo);await writeFile(join(repo,'README.md'),'# isolated worktree recovery\n');const git=promisify(execFile);for(const args of [['init'],['add','README.md'],['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-m','fixture']])await git('git',args,{cwd:repo});
    let snap=await f.snapshot();const project=await f.host.handle('project.create',{requestId:'project',expectedStoreRevision:snap.storeRevision,title:'目录恢复',directory:repo}) as {project:{id:string}};snap=await f.snapshot();const task=await f.host.handle('task.create',{requestId:'project-task',expectedStoreRevision:snap.storeRevision,scope:{kind:'project',projectId:project.project.id},title:'部分目录准备',goal:'保留已发生的目录创建'}) as TaskBundle;
    const store=(f.host as unknown as {productStore:ProductStore}).productStore,finish=store.finishManagedWorkerWorktree.bind(store);let interrupted=false;store.finishManagedWorkerWorktree=async input=>{if(!interrupted&&input.state==='ready'){interrupted=true;throw new Error('fixture: created directory but ready receipt missing');}return finish(input);};
    await f.host.handle('dcodeSession.prompt',{dcodeSessionId:task.coordinationSession.id,promptId:'dispatch',message:'安排独立目录工作'});await until(async()=>(await f.snapshot()).collaborationMessages?.some(message=>message.taskId===task.task.id&&message.state==='paused')??false,'failed preparation stays on the existing member');snap=await f.snapshot();const member=snap.agentRuns.find(run=>run.role==='worker')!,worktree=snap.managedWorkerWorktrees[0]!,message=snap.collaborationMessages!.find(message=>message.targetAgentRunId===member.id)!;assert.equal(workerCalls,0);assert.equal(worktree.state,'preparing');assert.ok(interrupted);await assert.rejects(f.host.handle('runtime.start',{runtimeId:'forged-worker',taskId:task.task.id,dcodeSessionId:member.sessionId,agentRunId:member.id,scope:task.task.scope,workspace:{workspaceId:'forged',cwd:repo,access:'exclusiveWrite'}}),/worktree|Worker|工作树|目录/i);
    await writeFile(join(worktree.workspaceCwd,'saved-before-recovery.md'),'已有成果不能被恢复覆盖');await mkdir(join(worktree.workspaceCwd,'node_modules','.cache'),{recursive:true});await writeFile(join(worktree.workspaceCwd,'node_modules','.cache','marker'),'dependency cache');
    await f.host.handle('collaboration.messageControl',{requestId:'resume-worktree',id:message.id,expectedRevision:message.revision,state:'queued'});await until(async()=>(await f.snapshot()).collaborationMessages?.some(item=>item.id===message.id&&item.state==='completed')??false,'verified worktree continues');await until(async()=>!(await f.snapshot()).collaborationMessages?.some(item=>['queued','delivering'].includes(item.state)),'result notifications settle');snap=await f.snapshot();assert.equal(workerCalls,2);assert.equal(snap.agentRuns.filter(run=>run.role==='worker').length,1);assert.equal(snap.managedWorkerWorktrees.length,1);const recovered=snap.managedWorkerWorktrees[0]!;assert.equal(recovered.state,'ready');assert.equal(recovered.managedPath,worktree.managedPath);assert.notEqual(recovered.provisionAttemptId,worktree.provisionAttemptId);assert.equal(snap.operationAttempts.find(attempt=>attempt.id===worktree.provisionAttemptId)!.status,'unknown');assert.equal(snap.operationAttempts.find(attempt=>attempt.id===recovered.provisionAttemptId)!.status,'succeeded');assert.equal(await readFile(join(recovered.workspaceCwd,'worker-result.md'),'utf8'),'在原工作树完成写入');await assert.rejects(readFile(join(repo,'worker-result.md'),'utf8'),{code:'ENOENT'});
    assert.equal(await readFile(join(recovered.workspaceCwd,'saved-before-recovery.md'),'utf8'),'已有成果不能被恢复覆盖');assert.equal(await readFile(join(recovered.workspaceCwd,'node_modules','.cache','marker'),'utf8'),'dependency cache');
    await f.restart();snap=await f.snapshot();assert.equal(snap.managedWorkerWorktrees[0]!.state,'ready');assert.equal(snap.managedWorkerWorktrees[0]!.workspaceCwd,recovered.workspaceCwd);assert.equal(await readFile(join(recovered.workspaceCwd,'saved-before-recovery.md'),'utf8'),'已有成果不能被恢复覆盖');assert.equal(await readFile(join(recovered.workspaceCwd,'node_modules','.cache','marker'),'utf8'),'dependency cache');assert.equal(await readFile(join(repo,'README.md'),'utf8'),'# isolated worktree recovery\n');await rm(recovered.managedPath,{recursive:true,force:true});await mkdir(recovered.workspaceCwd,{recursive:true});
    await assert.rejects(f.host.handle('runtime.start',{runtimeId:'tampered-worktree',taskId:task.task.id,dcodeSessionId:member.sessionId,agentRunId:member.id,scope:task.task.scope,workspace:{workspaceId:recovered.workspaceId,cwd:recovered.workspaceCwd,access:'exclusiveWrite'}}),error=>error instanceof Error&&'code' in error&&error.code==='WORKSPACE_MANAGED_WORKTREE_UNKNOWN');
    assert.equal((await f.snapshot()).managedWorkerWorktrees[0]!.state,'unknown');assert.equal((await f.snapshot()).managedWorkerWorktrees[0]!.failureCode,'WORKSPACE_WORKTREE_VERIFICATION_FAILED');

  }catch(error){console.error(JSON.stringify({workerCalls,errors:f.errors,snapshot:await f.snapshot()},null,2));throw error;}finally{await f.close();}
});
