import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,readdir,realpath,rename,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {WorkspaceFiles} from '../src/workspace-files.js';
import {PiHost} from '../src/pi-host.js';
import {ProductStore,type FoundationSnapshot,type TaskBundle,type ProjectRecord} from '../src/product-store.js';
import {directoryChangeTargets,swapProjectDirectories,type ProjectDirectoryChange} from '../src/project-directory-change.js';
const until=async(check:()=>Promise<boolean>)=>{const deadline=Date.now()+8000;while(!await check()){if(Date.now()>deadline)throw new Error('runtime did not settle');await new Promise(resolve=>setTimeout(resolve,20));}};
const completion=()=>new Response(`data: ${JSON.stringify({id:'project',object:'chat.completion.chunk',model:'fixture',created:1,choices:[{index:0,delta:{role:'assistant',content:'项目内容已核对'},finish_reason:null}]})}\n\ndata: ${JSON.stringify({id:'project',object:'chat.completion.chunk',model:'fixture',created:1,choices:[{index:0,delta:{},finish_reason:'stop'}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}})}\n\ndata: [DONE]\n\n`,{headers:{'content-type':'text/event-stream'}});

test('project rename and directory replacement preserve D Code conversations, keep original adapter bytes, and move files without merging targets',async()=>{
  const root=await mkdtemp(join(tmpdir(),'dcode-project-maintenance-')),agent=join(root,'agent'),home=join(root,'home'),source=join(home,'source'),target=join(home,'target'),moved=join(home,'moved');await mkdir(agent);await mkdir(home);await mkdir(source);await mkdir(target);await mkdir(moved);
  await writeFile(join(source,'original.md'),'原目录内容');await writeFile(join(target,'target.md'),'目标目录内容');
  await writeFile(join(agent,'settings.json'),JSON.stringify({defaultProvider:'project-fixture',defaultModel:'fixture'}));await writeFile(join(agent,'models.json'),JSON.stringify({providers:{'project-fixture':{baseUrl:'https://project.invalid/v1',api:'openai-completions',apiKey:'fixture-only',models:[{id:'fixture',name:'Fixture',reasoning:false,input:['text'],contextWindow:100000,maxTokens:4096}]}}}));
  const previousFetch=globalThis.fetch,requests:string[]=[];globalThis.fetch=(async(_url,init)=>{requests.push(String(init?.body));return completion();}) as typeof fetch;
  const options={agentDir:agent,sessionsDirectory:join(agent,'sessions'),dataRoot:join(root,'.dcode'),userHome:home,emit:()=>{}};let host=new PiHost(options);const snapshot=()=>host.handle('foundation.snapshot',{}) as Promise<FoundationSnapshot>;
  try {
    await host.start();let snap=await snapshot();let project=(await host.handle('project.create',{requestId:'project',expectedStoreRevision:snap.storeRevision,title:'原项目',directory:source}) as {project:ProjectRecord}).project;
    const rename={requestId:'rename',projectId:project.id,expectedProjectRevision:project.revision,title:'新项目名',directory:project.directory,moveFiles:false};project=(await host.handle('project.update',rename) as {project:ProjectRecord}).project;assert.equal(project.title,'新项目名');assert.equal((await host.handle('project.update',rename) as {project:ProjectRecord}).project.revision,project.revision);
    const task=await host.handle('task.create',{requestId:'task',expectedStoreRevision:(await snapshot()).storeRevision,scope:{kind:'project',projectId:project.id},title:'需要保留的对话',goal:'更换目录后继续'}) as TaskBundle;
    const send=async(id:string,message:string)=>{await host.handle('dcodeSession.prompt',{dcodeSessionId:task.coordinationSession.id,promptId:id,message});await until(async()=>!(await snapshot()).sessionRuns.some(run=>['prepared','running'].includes(run.status)));};
    await send('first','原有对话内容');snap=await snapshot();const binding=snap.sessionRuntimeBindings.find(binding=>binding.sessionId===task.coordinationSession.id)!;assert.ok(binding.adapterSessionPath.includes('/.dcode/runtime/pi-sessions/'));const originalBytes=await readFile(binding.adapterSessionPath);
    await assert.rejects(host.handle('project.update',{requestId:'nonempty',projectId:project.id,expectedProjectRevision:project.revision,title:project.title,directory:target,moveFiles:true}),/空的目标/);assert.equal(await readFile(join(source,'original.md'),'utf8'),'原目录内容');assert.equal(await readFile(join(target,'target.md'),'utf8'),'目标目录内容');
    const relocate={requestId:'directory',projectId:project.id,expectedProjectRevision:project.revision,title:project.title,directory:target,moveFiles:false};project=(await host.handle('project.update',relocate) as {project:ProjectRecord}).project;assert.equal(project.directory,await realpath(target));assert.equal((await host.handle('project.update',relocate) as {replayed:boolean}).replayed,true);
    snap=await snapshot();assert.equal(snap.tasks.find(item=>item.id===task.task.id)?.cwd,await realpath(target));assert.equal(snap.sessions.filter(session=>session.taskId===task.task.id).length,1);const next=snap.sessionRuntimeBindings.find(item=>item.sessionId===binding.sessionId)!;assert.notEqual(next.adapterSessionId,binding.adapterSessionId);assert.equal(next.cwd,await realpath(target));assert.deepEqual(await readFile(binding.adapterSessionPath),originalBytes);
    const file=await host.handle('workspace.read',{source:{taskId:task.task.id},path:'target.md'}) as {text:string};assert.equal(file.text,'目标目录内容');
    await send('continued','新目录继续');assert.ok(requests.at(-1)!.includes(await realpath(target)));assert.ok(requests.at(-1)!.includes('原有对话内容'));
    const beforeMove=(await snapshot()).projects.find(item=>item.id===project.id)!;project=(await host.handle('project.update',{requestId:'move-files',projectId:project.id,expectedProjectRevision:beforeMove.revision,title:project.title,directory:moved,moveFiles:true}) as {project:ProjectRecord}).project;
    assert.equal(project.directory,await realpath(moved));assert.deepEqual(await readdir(target),[]);assert.equal(await readFile(join(moved,'target.md'),'utf8'),'目标目录内容');assert.equal(await readFile(join(source,'original.md'),'utf8'),'原目录内容');
    await host.close();host=new PiHost(options);await host.start();snap=await snapshot();assert.equal(snap.projects.find(item=>item.id===project.id)?.directory,await realpath(moved));await send('restored','重启后继续');assert.ok(requests.at(-1)!.includes('原有对话内容'));assert.ok(requests.at(-1)!.includes('新目录继续'));
  }finally{await host.close();globalThis.fetch=previousFetch;await rm(root,{recursive:true,force:true});}
});

test('startup completes an already swapped directory from its durable plan and cancels a plan with no file effects',async()=>{
  const root=await mkdtemp(join(tmpdir(),'dcode-project-recovery-')),home=join(root,'home'),agent=join(root,'agent');await mkdir(home);await mkdir(agent);const dataRoot=join(root,'.dcode');let store=await ProductStore.open({dataRoot,userHome:home});
  try{
    for(const [name,swap] of [['swapped',true],['untouched',false]] as const){const source=join(home,`${name}-source`),target=join(home,`${name}-target`);await mkdir(source);await mkdir(target);await writeFile(join(source,'note.md'),name);const initial=await store.snapshot();const project=(await store.createProject({requestId:`project-${name}`,expectedStoreRevision:initial.storeRevision,title:name,directory:source})).project;const plan:ProjectDirectoryChange={id:`change-${name}`,projectId:project.id,expectedProjectRevision:project.revision,title:name,requestedDirectory:target,...await directoryChangeTargets(source,target,true),moveFiles:true,bindings:[],status:'prepared'};await store.prepareProjectDirectoryChange(plan);if(swap)await swapProjectDirectories(plan);}
    await store.close();const host=new PiHost({agentDir:agent,sessionsDirectory:join(agent,'sessions'),dataRoot,userHome:home,emit:()=>{}});try{await host.start();const snapshot=await host.handle('foundation.snapshot',{}) as FoundationSnapshot;assert.equal(snapshot.projectDirectoryChanges?.find(change=>change.id==='change-swapped')?.status,'committed');assert.equal(snapshot.projectDirectoryChanges?.find(change=>change.id==='change-untouched')?.status,'cancelled');assert.equal(snapshot.projects.find(project=>project.title==='swapped')?.directory,await realpath(join(home,'swapped-target')));assert.equal(await readFile(join(home,'swapped-target','note.md'),'utf8'),'swapped');assert.equal(await readFile(join(home,'untouched-source','note.md'),'utf8'),'untouched');}finally{await host.close();}
  }finally{await store.close();await rm(root,{recursive:true,force:true});}
});


test('directory moves reject nested registered projects and keep ambiguous swap results isolated until verified recovery',async()=>{
  const root=await mkdtemp(join(tmpdir(),'dcode-project-boundary-')),home=join(root,'home'),agent=join(root,'agent'),parent=join(home,'parent'),nested=join(parent,'nested'),target=join(home,'target');await mkdir(nested,{recursive:true});await mkdir(target);await mkdir(agent);await writeFile(join(nested,'keep.md'),'保留嵌套项目');
  await writeFile(join(agent,'settings.json'),JSON.stringify({defaultProvider:'fixture',defaultModel:'fixture'}));await writeFile(join(agent,'models.json'),JSON.stringify({providers:{fixture:{baseUrl:'https://fixture.invalid/v1',api:'openai-completions',apiKey:'fixture-only',models:[{id:'fixture',name:'Fixture',reasoning:false,input:['text'],contextWindow:100000,maxTokens:4096}]}}}));
  const options={agentDir:agent,sessionsDirectory:join(agent,'sessions'),dataRoot:join(root,'.dcode'),userHome:home,emit:()=>{}};let host=new PiHost(options);const snapshot=()=>host.handle('foundation.snapshot',{}) as Promise<FoundationSnapshot>;
  const original=WorkspaceFiles.prototype.swapDirectories;
  try{
    await host.start();const create=async(title:string,directory:string)=>(await host.handle('project.create',{requestId:`create-${title}`,expectedStoreRevision:(await snapshot()).storeRevision,title,directory}) as {project:ProjectRecord}).project;
    const a=await create('parent',parent);await create('nested',nested);
    await assert.rejects(host.handle('project.update',{requestId:'unsafe-parent',projectId:a.id,expectedProjectRevision:a.revision,title:a.title,directory:target,moveFiles:true}),/另一个已登记项目/);assert.equal(await readFile(join(nested,'keep.md'),'utf8'),'保留嵌套项目');assert.deepEqual(await readdir(target),[]);
    const protectedSource=join(agent,'retained-resource'),protectedTarget=join(root,'.dcode','empty-target');await mkdir(protectedSource);await mkdir(protectedTarget);await writeFile(join(protectedSource,'keep.md'),'运行资料不可搬走');const owned=await create('protected-source',protectedSource);
    await assert.rejects(host.handle('project.update',{requestId:'move-owned-source',projectId:owned.id,expectedProjectRevision:owned.revision,title:owned.title,directory:target,moveFiles:true}),/运行数据/);assert.equal(await readFile(join(protectedSource,'keep.md'),'utf8'),'运行资料不可搬走');
    const lateSource=join(home,'late-source'),lateChild=join(lateSource,'child');await mkdir(lateChild,{recursive:true});await writeFile(join(lateSource,'keep.md'),'保存准备前的文件');const late=await create('late-source',lateSource);
    await assert.rejects(host.handle('project.update',{requestId:'move-owned-target',projectId:late.id,expectedProjectRevision:late.revision,title:late.title,directory:protectedTarget,moveFiles:true}),/运行数据/);assert.equal(await readFile(join(lateSource,'keep.md'),'utf8'),'保存准备前的文件');assert.deepEqual(await readdir(protectedTarget),[]);
    const store=(host as unknown as {productStore:ProductStore}).productStore,prepare=store.prepareProjectDirectoryChange.bind(store);let registered=false;
    store.prepareProjectDirectoryChange=async change=>{if(!registered&&change.projectId===late.id){registered=true;await store.createProject({requestId:'late-child',expectedStoreRevision:(await store.snapshot()).storeRevision,title:'late child',directory:lateChild});}return prepare(change);};
    await assert.rejects(host.handle('project.update',{requestId:'late-registration',projectId:late.id,expectedProjectRevision:late.revision,title:late.title,directory:target,moveFiles:true}),/准备期间另一个项目/);store.prepareProjectDirectoryChange=prepare;assert.equal(await readFile(join(lateSource,'keep.md'),'utf8'),'保存准备前的文件');assert.deepEqual(await readdir(target),[]);
    const source=join(home,'source');await mkdir(source);await writeFile(join(source,'result.md'),'已交换的结果');const independent=await create('independent',source);const displaced=join(home,'displaced-empty');
    WorkspaceFiles.prototype.swapDirectories=async function(...args){await original.apply(this,args);await rename(args[0],displaced);};
    await assert.rejects(host.handle('project.update',{requestId:'uncertain-swap',projectId:independent.id,expectedProjectRevision:independent.revision,title:independent.title,directory:target,moveFiles:true}),/未能确认|结果/);
    WorkspaceFiles.prototype.swapDirectories=original;
    let snap=await snapshot();assert.equal(snap.projectDirectoryChanges?.find(change=>change.id==='uncertain-swap')?.status,'unknown');assert.equal(snap.projects.find(project=>project.id===independent.id)?.directory,await realpath(home)+'/source');assert.equal(await readFile(join(target,'result.md'),'utf8'),'已交换的结果');
    const userTask=await host.handle('task.create',{requestId:'outside-project',expectedStoreRevision:snap.storeRevision,scope:{kind:'user',userId:snap.currentUser.id},title:'其他作用域',goal:'不能穿过未确认迁移'}) as TaskBundle;
    const assertProtected=async()=>{
      const file=await host.handle('workspace.read',{source:{taskId:userTask.task.id},path:'target/result.md'}) as {digest:string;root:string};
      await assert.rejects(host.handle('workspace.save',{source:{taskId:userTask.task.id},path:'target/result.md',text:'must not overwrite unknown move',expectedDigest:file.digest,expectedRoot:file.root}),error=>(error as {code:string}).code==='WORKSPACE_IN_USE');
      await assert.rejects(host.handle('runtime.start',{runtimeId:'overlap-unknown-move',taskId:userTask.task.id,dcodeSessionId:userTask.coordinationSession.id,scope:userTask.task.scope,workspace:{workspaceId:'overlap',cwd:home,access:'exclusiveWrite'}}),error=>(error as {code:string}).code==='WORKSPACE_IN_USE');
      await assert.rejects(create('reserved-target',target),/尚未确认/);
      await assert.rejects(host.handle('project.update',{requestId:'rename-pending',projectId:independent.id,expectedProjectRevision:independent.revision,title:'不能破坏恢复修订',directory:independent.directory,moveFiles:false}),/等待恢复/);
    };
    await assertProtected();await host.close();host=new PiHost(options);await host.start();await assertProtected();assert.equal(await readFile(join(target,'result.md'),'utf8'),'已交换的结果');
    await rename(displaced,source);await host.handle('project.recover',{projectId:independent.id});snap=await snapshot();assert.equal(snap.projectDirectoryChanges?.find(change=>change.id==='uncertain-swap')?.status,'committed');assert.equal(snap.projects.find(project=>project.id===independent.id)?.directory,await realpath(target));
    const file=await host.handle('workspace.read',{source:{taskId:userTask.task.id},path:'target/result.md'}) as {digest:string;root:string};await host.handle('workspace.save',{source:{taskId:userTask.task.id},path:'target/result.md',text:'恢复确认后可保存',expectedDigest:file.digest,expectedRoot:file.root});assert.equal(await readFile(join(target,'result.md'),'utf8'),'恢复确认后可保存');await host.handle('runtime.start',{runtimeId:'after-directory-recovery',taskId:userTask.task.id,dcodeSessionId:userTask.coordinationSession.id,scope:userTask.task.scope,workspace:{workspaceId:'after-recovery',cwd:home,access:'exclusiveWrite'}});await host.handle('session.close',{runtimeId:'after-directory-recovery'});
  }finally{WorkspaceFiles.prototype.swapDirectories=original;await host.close();await rm(root,{recursive:true,force:true});}
});
