import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {PiHost} from '../src/pi-host.js';
import type {FoundationSnapshot,TaskBundle,TaskContextSourceInput} from '../src/product-store.js';
const until=async(check:()=>Promise<boolean>,label:string)=>{const deadline=Date.now()+12000;while(!await check()){if(Date.now()>deadline)throw new Error(label);await new Promise(resolve=>setTimeout(resolve,30));}};
const answer=(text:string,action?:unknown)=>new Response(`data: ${JSON.stringify({id:'fixture',object:'chat.completion.chunk',created:1,model:'fixture',choices:[{index:0,delta:action?{role:'assistant',tool_calls:[{index:0,id:'delegate',type:'function',function:{name:'dcode_team',arguments:JSON.stringify(action)}}]}:{role:'assistant',content:text},finish_reason:null}]})}\n\ndata: ${JSON.stringify({id:'fixture',object:'chat.completion.chunk',choices:[{index:0,delta:{},finish_reason:action?'tool_calls':'stop'}],usage:{prompt_tokens:1,completion_tokens:1,total_tokens:2}})}\n\ndata: [DONE]\n\n`,{headers:{'content-type':'text/event-stream'}});

test('context selection changes apply to later runs while current documents stay frozen across tool-set changes',async()=>{
  const root=await mkdtemp(join(tmpdir(),'dcode-context-receipts-')),agent=join(root,'agent'),home=join(root,'home');await mkdir(agent);await mkdir(home);await writeFile(join(home,'AGENTS.md'),'Keep the original user input.');await writeFile(join(home,'first.md'),'FIRST_SELECTED_SOURCE');await writeFile(join(home,'second.md'),'SECOND_SELECTED_SOURCE');await writeFile(join(root,'outside.md'),'outside');await writeFile(join(home,'large.md'),'x'.repeat(65537));await writeFile(join(home,'.env'),'DO_NOT_LOAD=fixture');
  await writeFile(join(agent,'settings.json'),JSON.stringify({defaultProvider:'zai-coding-cn',defaultModel:'fixture'}));await writeFile(join(agent,'models.json'),JSON.stringify({providers:{'zai-coding-cn':{baseUrl:'https://open.bigmodel.cn/api/paas/v4',api:'openai-completions',apiKey:'fixture-only',models:[{id:'fixture',name:'Fixture',reasoning:false,input:['text'],contextWindow:100000,maxTokens:4096}]}}}));
  const previous=globalThis.fetch;let release!:()=>void;const held=new Promise<void>(resolve=>{release=resolve;});let mainCalls=0;const mainPrompts:string[]=[];
  globalThis.fetch=(async(url,init)=>{if(String(url).includes('quota/limit'))return Response.json({success:true,code:200,data:{limits:[{type:'TOKENS_LIMIT',percentage:10,nextResetTime:Date.now()+3600000}]}});const body=JSON.parse(String(init?.body)),system=body.messages.find((message:any)=>message.role==='system').content;if(system.includes('coordinator Agent')){mainCalls++;mainPrompts.push(system);if(mainCalls===1){await held;return answer('',{action:'delegate',members:[{profileId:'builtin-explore',title:'独立检查',instruction:'读取新运行的选定资料',acceptance:'明确来源'}]});}return answer('本轮按开始时的资料处理，后续运行使用新选择');}assert.ok(system.includes('SECOND_SELECTED_SOURCE'));assert.ok(!system.includes('FIRST_SELECTED_SOURCE'));return answer('新成员使用新选择');}) as typeof fetch;
  const host=new PiHost({agentDir:agent,sessionsDirectory:join(agent,'sessions'),dataRoot:join(root,'.dcode'),userHome:home,emit:()=>{}}),snapshot=()=>host.handle('foundation.snapshot',{}) as Promise<FoundationSnapshot>;
  try{
    await host.start();let snap=await snapshot();const task=await host.handle('task.create',{requestId:'task',expectedStoreRevision:snap.storeRevision,scope:{kind:'user',userId:snap.currentUser.id},title:'资料版本检查',goal:'下一次运行生效'}) as TaskBundle;
    const inspected=await host.handle('task.context.inspectFiles',{taskId:task.task.id,paths:[join(home,'AGENTS.md'),join(home,'first.md'),join(home,'first.md')]}) as {sources:TaskContextSourceInput[];requiredAgents:boolean};assert.ok(inspected.requiredAgents);assert.equal(inspected.sources.length,1);
    for(const file of [join(root,'outside.md'),join(home,'large.md'),join(home,'.env')])await assert.rejects(host.handle('task.context.inspectFiles',{taskId:task.task.id,paths:[file]}));
    snap=await snapshot();await host.handle('task.context.replace',{requestId:'first-context',expectedStoreRevision:snap.storeRevision,taskId:task.task.id,scope:task.task.scope,expectedContextRevision:snap.taskContextSets[0]!.revision,sources:inspected.sources});
    await host.handle('dcodeSession.prompt',{dcodeSessionId:task.coordinationSession.id,promptId:'initial',message:'从已选资料开始检查'});await until(async()=>mainCalls===1,'initial provider call is active');snap=await snapshot();const firstRun=snap.sessionRuns[0]!,receipt=snap.promptReceipts.find(receipt=>receipt.sessionRunId===firstRun.id)!;
    await writeFile(join(home,'first.md'),'CHANGED_ON_DISK');const second=await host.handle('task.context.inspectFiles',{taskId:task.task.id,paths:[join(home,'second.md')]}) as {sources:TaskContextSourceInput[]};snap=await snapshot();await host.handle('task.context.replace',{requestId:'next-context',expectedStoreRevision:snap.storeRevision,taskId:task.task.id,scope:task.task.scope,expectedContextRevision:snap.taskContextSets[0]!.revision,sources:second.sources});
    release();await until(async()=>(await snapshot()).collaborationMessages?.some(message=>message.author==='member'&&message.state==='completed')??false,'new member and coordinator follow-up settle');snap=await snapshot();assert.ok(mainPrompts[0]!.includes('FIRST_SELECTED_SOURCE'));assert.ok(mainPrompts[1]!.includes('FIRST_SELECTED_SOURCE'));assert.ok(!mainPrompts[1]!.includes('CHANGED_ON_DISK'));assert.ok(!mainPrompts[1]!.includes('SECOND_SELECTED_SOURCE'));assert.ok(mainPrompts.slice(2).some(prompt=>prompt.includes('SECOND_SELECTED_SOURCE')));
    assert.deepEqual(snap.promptReceipts.find(item=>item.id===receipt.id)!.sourceReceipts,receipt.sourceReceipts,'the original source receipts are immutable');const calls=snap.providerCalls!.filter(call=>call.sessionRunId===firstRun.id);assert.equal(calls.length,2);assert.ok(calls[0]!.toolNames?.includes('write'));assert.ok(!calls[1]!.toolNames?.includes('write'));assert.notEqual(calls[0]!.toolManifestDigest,calls[1]!.toolManifestDigest);
    const inputs=await host.handle('sessionRun.inputs',{taskId:task.task.id,sessionRunId:firstRun.id}) as {rawText:string};assert.equal(inputs.rawText,'从已选资料开始检查');
  }finally{release();await host.close();globalThis.fetch=previous;await rm(root,{recursive:true,force:true});}
});
